import { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react';
import { useUserSettings } from '@/hooks/useUserSettings';

export type Language = 'en' | 'ar' | 'fr' | 'zh' | 'ja' | 'hi' | 'es' | 'pt';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  en: {
    // Navigation
    home: 'Home', studyMaterials: 'Study Materials', vocabulary: 'Vocabulary',
    createTable: 'Create Table', pomodoroTimer: 'Pomodoro Timer',
    suggestions: 'Suggestions', messages: 'Messages', todoList: 'To-Do List', technicalSupport: 'Technical Support',
    // Settings
    settings: 'Settings', profile: 'Profile', displayName: 'Display Name',
    save: 'Save', avatarColor: 'Avatar Color', avatarIcon: 'Avatar Icon',
    changePassword: 'Change Password', newPassword: 'New password...',
    confirmPassword: 'Confirm new password...',
    appearance: 'Appearance', darkMode: 'Dark Mode', darkEnabled: 'Dark theme enabled',
    lightEnabled: 'Light theme enabled', sidebarOrder: 'Sidebar Order',
    sidebarDrag: 'Drag and drop to reorder the sidebar navigation buttons.',
    saveSidebarOrder: 'Save Sidebar Order', account: 'Account',
    signOutDesc: 'Sign out of your account on this device.', signOut: 'Sign Out',
    language: 'Language', languageDesc: 'Choose your preferred language',
    // Vocabulary
    addWord: 'Add Word', practice: 'Practice', difficult: 'Difficult',
    search: 'Search...', masteryProgress: 'Mastery Progress',
    words: 'words', mastered: 'mastered', noDifficultWords: 'No difficult words',
    noWordsFound: 'No words found', noWordsYet: 'No words yet',
    greatNoDifficult: 'Great! No words are marked as difficult',
    tryDifferentSearch: 'Try a different search term',
    addFirstWord: 'Add your first vocabulary word to get started',
    showingDifficult: 'Showing difficult words that need more review',
    searchingFor: 'Searching for', result: 'result', results: 'results',
    // Auth
    signIn: 'Sign In / Create Account', myProfile: 'My Profile',
    signInBtn: 'Sign In', createAccountBtn: 'Create Account',
    welcomeBack: 'Welcome back', createYourAccount: 'Create your account',
    continueYourJourney: 'Continue your learning journey',
    startYourJourney: 'Start your learning journey today',
    email: 'Email', password: 'Password', confirmPasswordLabel: 'Confirm Password',
    howShouldWeCallYou: 'How should we call you?',
    dontHaveAccount: "Don't have an account?", signUpLink: 'Sign up',
    alreadyHaveAccount: 'Already have an account?', signInLink: 'Sign in',
    backToHome: 'Back to home', loading: 'Loading...',
    learnSmarter: 'Learn Smarter, Study Better',
    authFeatureDesc: 'Smart organization, focused study sessions, and powerful tools — everything you need to excel.',
    emailNotAvailable: 'This email address is not available for registration',
    displayNameRequired: 'Please enter a display name',
    signupFailed: 'Failed to create account', signinFailed: 'Failed to sign in',
    accountCreated: 'Account created successfully!', signedIn: 'Signed in successfully!',
    signInToUse: 'Sign in to use',
    // Offline
    youAreOffline: 'You are offline — data is saved locally', hide: 'Hide',
    // Settings misc
    changingPassword: 'Changing...',
    passwordChanged: 'Password changed successfully', passwordsDontMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    displayNameUpdated: 'Display name updated',
    sidebarOrderSaved: 'Sidebar order saved',
    // Flashcards
    testComplete: 'Test Complete!', wordsReviewed: 'words reviewed',
    easy: 'Easy', hard: 'Hard', failed: 'Failed', wordsToReview: 'Words to Review',
    testAgain: 'Test Again', backToVocabulary: 'Back to Vocabulary',
    numberOfWords: 'Number of Words', testType: 'Test Type', testFormat: 'Test Format',
    flashcards: 'Flashcards', multipleChoice: 'Multiple Choice',
    flipToReveal: 'Flip to reveal meaning', pickCorrect: 'Pick the correct answer',
    random: 'Random', focus: 'Focus', smartReview: 'Smart Review',
    randomDesc: 'Random selection of words', focusDesc: 'Only words rated poor or difficult',
    smartDesc: 'Words needing review based on algorithm', startTest: 'Start Test',
    byDate: 'By Date', byDateDesc: 'Quiz words added on a specific day', selectDate: 'Select a date', noDatesAvailable: 'No dates available',
    whatDoesWordMean: 'What does this word mean?', needsMorePractice: 'Needs more practice',
    back: 'Back',
    typing: 'Typing', typingDesc: 'Type the meaning from memory',
    typeMeaning: 'Type the meaning', typeYourAnswer: 'Type your answer...',
    checkAnswer: 'Check Answer', correct: '✓ Correct!', incorrect: '✗ Incorrect',
    offlineMode: 'Offline mode — using cached vocabulary', offline: 'Offline',
    // Home page
    yourUltimate: 'Your Ultimate', studyCompanion: 'Study Companion',
    homeDesc: 'Smart tools, organized materials, and focused study sessions — everything you need to ace your studies, all in one place.',
    getStartedFree: 'Get Started Free', features: 'Features',
    everythingYouNeed: 'Everything You Need to Succeed',
    readyToTransform: 'Ready to Transform Your Study Habits?',
    joinStudents: 'Join students who are already using StudyHub to organize, focus, and succeed in their academic journey.',
    createFreeAccount: 'Create Your Free Account',
    welcomeBackUser: 'Welcome back,',
    homeWelcomeDesc: 'StudyHub is your all-in-one academic toolkit. Organize your course materials, stay focused with Pomodoro sessions, and build your vocabulary — all synced across your devices.',
    goToMaterials: 'Go to My Materials',
    installApp: '📱 Install this app on your device for offline access',
    // Feature titles
    organizeMaterials: 'Organize Materials',
    organizeMaterialsDesc: 'Keep all your courses, lessons, and files perfectly organized in one place with progress tracking.',
    pomodoroTimerTitle: 'Pomodoro Timer',
    pomodoroTimerDesc: 'Stay focused with customizable study sessions, break intervals, and ambient nature sounds.',
    vocabFlashcards: 'Vocabulary & Flashcards',
    vocabFlashcardsDesc: 'Build your vocabulary with spaced repetition flashcards and track your memorization progress.',
    // Materials page
    signInToViewMaterials: 'Sign in to view materials',
    createAccountToSave: 'Create an account to save and sync your study materials',
    addMaterial: 'Add Material', noMaterialsYet: 'No materials yet',
    addFirstMaterial: 'Add your first study material to get started!',
    // Todo page
    addTask: 'Add Task', total: 'Total', completed: 'Completed', urgent: 'Urgent', overdue: 'Overdue',
    taskTitle: 'Task title...', taskDescription: 'Description (optional)',
    deadline: 'Deadline', importance: 'Importance',
    urgentLabel: 'Urgent', mediumLabel: 'Medium', lowLabel: 'Low',
    noTasks: 'No tasks yet', addFirstTask: 'Add your first task to get started',
    signInForTodos: 'Sign in to use To-Do List',
    // Messages page
    messagesTitle: 'Messages & Polls', noMessages: 'No messages yet',
    markAllRead: 'Mark all read',
    // Suggestions page
    suggestionsTitle: 'Suggestions', addSuggestion: 'Add Suggestion',
    suggestionTitle: 'Title', suggestionDesc: 'Description',
    noSuggestions: 'No suggestions yet', submitSuggestion: 'Submit',
    // Pomodoro
    study: 'Study', shortBreak: 'Short Break', longBreak: 'Long Break',
    // Vocabulary dialog & card
    addNewWord: 'Add New Word', englishWord: 'English Word', enterEnglishWord: 'Enter the English word...',
    meaningLabel: 'Meaning', enterMeaning: 'Enter the meaning...', notesOptional: 'Notes (Optional)',
    addNotes: 'Add any additional notes...', adding: 'Adding...', letters: 'letters',
    english: 'ENGLISH', targetLanguage: 'MEANING',
    // === NEW KEYS for full translation ===
    // Messages page
    activePolls: 'Active Polls', messagesSection: 'Messages',
    noMessagesDesc: 'Messages and polls from the admin team will appear here',
    thankYouVote: 'Thank you for contributing to the site\'s development! 🎉',
    failedToVote: 'Failed to vote', adminMessage: 'Admin Message',
    // Suggestions page
    helpUsImprove: 'Help us improve the platform',
    beFirstToShare: 'Be the first to share your ideas!',
    shareYourIdea: 'Share Your Idea', relatedPage: 'Related Page',
    briefTitle: 'Brief title for your suggestion...',
    describeInDetail: 'Describe your suggestion in detail...',
    submitting: 'Submitting...', submitSuggestionBtn: 'Submit Suggestion',
    supported: 'Supported', supportThisIdea: 'Support this idea',
    accepted: 'Accepted', anonymous: 'Anonymous',
    // Page options for suggestions
    pageGeneral: 'General', pageMaterials: 'Study Materials', pageVocabulary: 'Vocabulary',
    pagePomodoro: 'Pomodoro Timer', pageMessages: 'Messages',
    pageSettings: 'Settings', pageSuggestions: 'Suggestions',
    // Pomodoro
    focusZone: 'Focus Zone',
    // Materials page
    subjects: 'subjects', subject: 'subject', addCourse: 'Add Course',
    noCoursesYet: 'No courses yet', addFirstCourse: 'Add your first course to get started',
    // Material detail
    backToMaterials: 'Back to Materials', materialNotFound: 'Material not found',
    completedLessons: 'completed', remainingLessons: 'remaining',
    lessons: 'Lessons', files: 'Files', hasNotes: 'Has notes',
    deleteMaterialConfirm: 'Are you sure you want to delete this material and all its lessons?',
    deleteLessonConfirm: 'Delete this lesson?',
    // Todo page
    toDoList: 'To-Do List', stayOrganized: 'Stay organized and track your progress',
    totalTasks: 'Total Tasks', overallProgress: 'Overall Progress',
    active: 'Active', done: 'Done',
    allClear: 'All clear!', addFirstTaskDesc: 'Add your first task to start tracking your progress',
    createFirstTask: 'Create First Task',
    addNewTask: 'Add New Task', title: 'Title', details: 'Details',
    whatNeedsToBeDone: 'What needs to be done?', addMoreContext: 'Add more context...',
    priority: 'Priority', dueDate: 'Due Date', add: 'Add',
    overdueWarning: 'This task is past its deadline!',
    signInToManageTasks: 'Sign in to manage your tasks',
    due: 'Due',
    // Support page
    signInToAccessSupport: 'Sign in to access Technical Support',
    createAccountForHelp: 'Create an account to get help from our team',
    getHelpFromTeam: 'Get help from our team',
    newTicket: 'New Ticket', open: 'Open', resolved: 'Resolved',
    noTicketsYet: 'No tickets yet', createTicketHelp: 'Create a ticket to get help from our team',
    createFirstTicket: 'Create First Ticket',
    newSupportTicket: 'New Support Ticket',
    subjectLabel: 'Subject', briefIssueDesc: 'Brief description of your issue...',
    messageLabel: 'Message', describeIssueDetail: 'Describe your issue in detail...',
    characters: 'characters', creating: 'Creating...', submitTicket: 'Submit Ticket',
    noMessagesYetChat: 'No messages yet — start the conversation!',
    typeYourMessage: 'Type your message...',
    // Flashcards
    signInToPractice: 'Sign in to practice',
    createAccountForFlashcards: 'Create an account to use flashcard practice',
    allWords: 'All',
    // Support description in settings
    supportDesc: 'Need help? Create a support ticket and our team will assist you.',
    codeCopied: 'Code copied!', yourUniqueCode: 'Your Unique Code',
    // Celebration phrases (todo)
    greatJob: "Great job! You're on fire! 🔥",
    taskCompleted: "Task completed! Keep going! 💪",
    wellDone: "Well done! One step closer! 🎯",
    amazing: "Amazing! You're crushing it! ⭐",
    incredibleProgress: "Incredible progress! 🚀",
    // Site guide
    siteGuideTitle: 'Site Guide',
    siteGuideSubtitle: 'Discover all features',
    infoHome: 'Your personal dashboard showing study statistics, recent activity, and quick access to all features. Track your daily progress and stay motivated.',
    infoMaterials: 'Organize your courses into structured modules. Add lessons with rich text, write detailed notes, upload files, and export as PDFs.',
    infoVocabulary: 'Build and manage your vocabulary. Add words with meanings and notes, practice with flashcards or quizzes, and track mastery with spaced repetition.',
    infoPomodoro: 'Stay focused using the Pomodoro technique. Customize study and break durations, choose color themes, and set alarm sounds.',
    infoMessages: 'Read announcements and updates from the admin. Like messages, participate in polls, and stay informed about new features.',
    infoSuggestions: 'Share your ideas to improve the platform. Submit feature requests, vote on others\' suggestions, and help shape the experience.',
    infoTodos: 'Manage tasks with color-coded priorities (Urgent, Medium, Low). Set deadlines with live countdowns, track progress, and celebrate achievements.',
    infoSupport: 'Need help? Create support tickets, attach images, chat with the team, and track your issue until it\'s resolved.',
    leaderboard: 'Leaderboard',
    leaderboardDesc: 'Top performers by XP earned',
    noLeaderboardData: 'No data yet',
    goToMessage: 'Go to Message',
    pinned: 'Pinned',
    // New keys
    pause: 'Pause', start: 'Start',
    alarmSound: 'Alarm Sound',
    alarmChime: 'Chime', alarmBell: 'Bell', alarmDigital: 'Digital', alarmGentle: 'Gentle', alarmNature: 'Nature',
    motivational1: 'Stay focused, success is built one moment at a time.',
    motivational2: 'Your dedication today shapes your tomorrow.',
    motivational3: 'Small steps lead to big achievements.',
    motivational4: 'Embrace the process, trust the journey.',
    internetOutage: 'No Internet Connection',
    viewingAs: 'Viewing as',
    returnToAdmin: 'Return to Admin',
    leaderboardHowTo: 'How to Rank Up',
    leaderboardRule1Title: 'Earn XP Points', leaderboardRule1Desc: 'Complete tasks and activities to earn experience points.',
    leaderboardRule2Title: 'Stay Consistent', leaderboardRule2Desc: 'Log in daily and complete your study sessions.',
    leaderboardRule3Title: 'Reach the Top', leaderboardRule3Desc: 'Top 3 performers earn Gold, Silver, and Bronze crowns.',
    addLesson: 'Add Lesson', progress: 'Progress', uploadFile: 'Upload File',
    selectIcon: 'Select Icon', courseName: 'Course Name', courseNamePlaceholder: 'Enter course name...',
  },
  ar: {
    home: 'الرئيسية', studyMaterials: 'المواد الدراسية', vocabulary: 'المفردات',
    createTable: 'إنشاء جدول', pomodoroTimer: 'مؤقت بومودورو',
    suggestions: 'الاقتراحات', messages: 'الرسائل', todoList: 'قائمة المهام', technicalSupport: 'الدعم الفني',
    settings: 'الإعدادات', profile: 'الملف الشخصي', displayName: 'اسم العرض',
    save: 'حفظ', avatarColor: 'لون الصورة الرمزية', avatarIcon: 'أيقونة الصورة الرمزية',
    changePassword: 'تغيير كلمة المرور', newPassword: 'كلمة المرور الجديدة...',
    confirmPassword: 'تأكيد كلمة المرور...',
    appearance: 'المظهر', darkMode: 'الوضع الداكن', darkEnabled: 'الوضع الداكن مفعّل',
    lightEnabled: 'الوضع الفاتح مفعّل', sidebarOrder: 'ترتيب الشريط الجانبي',
    sidebarDrag: 'اسحب وأفلت لإعادة ترتيب أزرار التنقل.',
    saveSidebarOrder: 'حفظ ترتيب الشريط الجانبي', account: 'الحساب',
    signOutDesc: 'تسجيل الخروج من حسابك على هذا الجهاز.', signOut: 'تسجيل الخروج',
    language: 'اللغة', languageDesc: 'اختر لغتك المفضلة',
    addWord: 'إضافة كلمة', practice: 'تدريب', difficult: 'صعبة',
    search: 'ابحث...', masteryProgress: 'تقدم الإتقان',
    words: 'كلمات', mastered: 'تم إتقانها', noDifficultWords: 'لا توجد كلمات صعبة',
    noWordsFound: 'لم يتم العثور على كلمات', noWordsYet: 'لا توجد كلمات بعد',
    greatNoDifficult: 'رائع! لا توجد كلمات مصنفة كصعبة',
    tryDifferentSearch: 'جرّب مصطلح بحث مختلف',
    addFirstWord: 'أضف أول كلمة مفردات للبدء',
    showingDifficult: 'عرض الكلمات الصعبة التي تحتاج مراجعة',
    searchingFor: 'البحث عن', result: 'نتيجة', results: 'نتائج',
    signIn: 'تسجيل الدخول / إنشاء حساب', myProfile: 'ملفي الشخصي',
    signInBtn: 'تسجيل الدخول', createAccountBtn: 'إنشاء حساب',
    welcomeBack: 'مرحباً بعودتك', createYourAccount: 'إنشاء حسابك',
    continueYourJourney: 'تابع رحلة تعلمك',
    startYourJourney: 'ابدأ رحلة تعلمك اليوم',
    email: 'البريد الإلكتروني', password: 'كلمة المرور', confirmPasswordLabel: 'تأكيد كلمة المرور',
    howShouldWeCallYou: 'ماذا نناديك؟',
    dontHaveAccount: 'ليس لديك حساب؟', signUpLink: 'إنشاء حساب',
    alreadyHaveAccount: 'لديك حساب بالفعل؟', signInLink: 'تسجيل الدخول',
    backToHome: 'العودة للرئيسية', loading: 'جارٍ التحميل...',
    learnSmarter: 'تعلّم بذكاء، ادرس بكفاءة',
    authFeatureDesc: 'تنظيم ذكي وجلسات دراسة مركّزة وأدوات قوية — كل ما تحتاجه للتفوق.',
    emailNotAvailable: 'هذا البريد الإلكتروني غير متاح للتسجيل',
    displayNameRequired: 'يرجى إدخال اسم العرض',
    signupFailed: 'فشل في إنشاء الحساب', signinFailed: 'فشل في تسجيل الدخول',
    accountCreated: 'تم إنشاء الحساب بنجاح!', signedIn: 'تم تسجيل الدخول بنجاح!',
    signInToUse: 'سجّل الدخول للاستخدام',
    youAreOffline: 'أنت غير متصل — البيانات محفوظة محلياً', hide: 'إخفاء',
    changingPassword: 'جارٍ التغيير...',
    passwordChanged: 'تم تغيير كلمة المرور بنجاح', passwordsDontMatch: 'كلمات المرور غير متطابقة',
    passwordTooShort: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    displayNameUpdated: 'تم تحديث اسم العرض',
    sidebarOrderSaved: 'تم حفظ ترتيب الشريط الجانبي',
    testComplete: 'اكتمل الاختبار!', wordsReviewed: 'كلمات تمت مراجعتها',
    easy: 'سهل', hard: 'صعب', failed: 'فشل', wordsToReview: 'كلمات للمراجعة',
    testAgain: 'اختبار مرة أخرى', backToVocabulary: 'العودة للمفردات',
    numberOfWords: 'عدد الكلمات', testType: 'نوع الاختبار', testFormat: 'تنسيق الاختبار',
    flashcards: 'بطاقات تعليمية', multipleChoice: 'اختيار من متعدد',
    flipToReveal: 'اقلب لكشف المعنى', pickCorrect: 'اختر الإجابة الصحيحة',
    random: 'عشوائي', focus: 'تركيز', smartReview: 'مراجعة ذكية',
    randomDesc: 'اختيار عشوائي للكلمات', focusDesc: 'فقط الكلمات المصنفة ضعيفة أو صعبة',
    smartDesc: 'كلمات تحتاج مراجعة حسب الخوارزمية', startTest: 'ابدأ الاختبار',
    byDate: 'حسب التاريخ', byDateDesc: 'اختبار الكلمات المضافة في يوم محدد', selectDate: 'اختر تاريخاً', noDatesAvailable: 'لا توجد تواريخ متاحة',
    whatDoesWordMean: 'ماذا تعني هذه الكلمة؟', needsMorePractice: 'تحتاج مزيداً من التدريب',
    back: 'رجوع',
    typing: 'كتابة', typingDesc: 'اكتب المعنى من الذاكرة',
    typeMeaning: 'اكتب المعنى', typeYourAnswer: 'اكتب إجابتك...',
    checkAnswer: 'تحقق من الإجابة', correct: '✓ صحيح!', incorrect: '✗ خطأ',
    offlineMode: 'وضع عدم الاتصال — استخدام المفردات المحفوظة', offline: 'غير متصل',
    yourUltimate: 'رفيقك الأمثل', studyCompanion: 'في الدراسة',
    homeDesc: 'أدوات ذكية، تنظيم متقدم، وجلسات دراسة مركّزة — كل ما تحتاجه للتفوق في دراستك.',
    getStartedFree: 'ابدأ مجاناً', features: 'المميزات',
    everythingYouNeed: 'كل ما تحتاجه للنجاح',
    readyToTransform: 'مستعد لتحويل عاداتك الدراسية؟',
    joinStudents: 'انضم للطلاب الذين يستخدمون StudyHub للتنظيم والتركيز والنجاح.',
    createFreeAccount: 'أنشئ حسابك المجاني',
    welcomeBackUser: 'مرحباً بعودتك،',
    homeWelcomeDesc: 'StudyHub هو مجموعة أدواتك الأكاديمية الشاملة. نظّم موادك الدراسية، حافظ على تركيزك مع جلسات بومودورو، وابنِ مفرداتك — كلها متزامنة عبر أجهزتك.',
    goToMaterials: 'اذهب لموادي',
    installApp: '📱 ثبّت هذا التطبيق على جهازك للوصول بدون إنترنت',
    organizeMaterials: 'تنظيم المواد',
    organizeMaterialsDesc: 'احتفظ بكل دروسك وملفاتك منظمة في مكان واحد مع تتبع التقدم.',
    pomodoroTimerTitle: 'مؤقت بومودورو',
    pomodoroTimerDesc: 'حافظ على تركيزك مع جلسات دراسة قابلة للتخصيص وفترات راحة وأصوات طبيعية.',
    vocabFlashcards: 'المفردات والبطاقات التعليمية',
    vocabFlashcardsDesc: 'ابنِ مفرداتك ببطاقات التكرار المتباعد وتتبع تقدمك في الحفظ.',
    signInToViewMaterials: 'سجّل الدخول لعرض المواد',
    createAccountToSave: 'أنشئ حساباً لحفظ ومزامنة موادك الدراسية',
    addMaterial: 'إضافة مادة', noMaterialsYet: 'لا توجد مواد بعد',
    addFirstMaterial: 'أضف أول مادة دراسية للبدء!',
    addTask: 'إضافة مهمة', total: 'الإجمالي', completed: 'مكتمل', urgent: 'عاجل', overdue: 'متأخر',
    taskTitle: 'عنوان المهمة...', taskDescription: 'الوصف (اختياري)',
    deadline: 'الموعد النهائي', importance: 'الأهمية',
    urgentLabel: 'عاجل', mediumLabel: 'متوسط', lowLabel: 'منخفض',
    noTasks: 'لا توجد مهام بعد', addFirstTask: 'أضف أول مهمة للبدء',
    signInForTodos: 'سجّل الدخول لاستخدام قائمة المهام',
    messagesTitle: 'الرسائل والاستطلاعات', noMessages: 'لا توجد رسائل بعد',
    markAllRead: 'تحديد الكل كمقروء',
    suggestionsTitle: 'الاقتراحات', addSuggestion: 'إضافة اقتراح',
    suggestionTitle: 'العنوان', suggestionDesc: 'الوصف',
    noSuggestions: 'لا توجد اقتراحات بعد', submitSuggestion: 'إرسال',
    study: 'دراسة', shortBreak: 'استراحة قصيرة', longBreak: 'استراحة طويلة',
    addNewWord: 'إضافة كلمة جديدة', englishWord: 'الكلمة بالإنجليزية', enterEnglishWord: 'أدخل الكلمة بالإنجليزية...',
    meaningLabel: 'المعنى', enterMeaning: 'أدخل المعنى...', notesOptional: 'ملاحظات (اختياري)',
    addNotes: 'أضف ملاحظات إضافية...', adding: 'جارٍ الإضافة...', letters: 'حروف',
    english: 'الإنجليزية', targetLanguage: 'المعنى',
    // New keys
    activePolls: 'الاستطلاعات النشطة', messagesSection: 'الرسائل',
    noMessagesDesc: 'ستظهر هنا الرسائل والاستطلاعات من فريق الإدارة',
    thankYouVote: 'شكراً لمساهمتك في تطوير الموقع! 🎉',
    failedToVote: 'فشل في التصويت', adminMessage: 'رسالة من الإدارة',
    helpUsImprove: 'ساعدنا في تحسين المنصة',
    beFirstToShare: 'كن أول من يشارك أفكاره!',
    shareYourIdea: 'شارك فكرتك', relatedPage: 'الصفحة المتعلقة',
    briefTitle: 'عنوان مختصر لاقتراحك...',
    describeInDetail: 'صف اقتراحك بالتفصيل...',
    submitting: 'جارٍ الإرسال...', submitSuggestionBtn: 'إرسال الاقتراح',
    supported: 'تم الدعم', supportThisIdea: 'ادعم هذه الفكرة',
    accepted: 'مقبول', anonymous: 'مجهول',
    pageGeneral: 'عام', pageMaterials: 'المواد الدراسية', pageVocabulary: 'المفردات',
    pagePomodoro: 'مؤقت بومودورو', pageMessages: 'الرسائل',
    pageSettings: 'الإعدادات', pageSuggestions: 'الاقتراحات',
    focusZone: 'منطقة التركيز',
    subjects: 'مواد', subject: 'مادة', addCourse: 'إضافة مادة دراسية',
    noCoursesYet: 'لا توجد مواد بعد', addFirstCourse: 'أضف أول مادة دراسية للبدء',
    backToMaterials: 'العودة للمواد', materialNotFound: 'المادة غير موجودة',
    completedLessons: 'مكتملة', remainingLessons: 'متبقية',
    lessons: 'الدروس', files: 'الملفات', hasNotes: 'يحتوي ملاحظات',
    deleteMaterialConfirm: 'هل أنت متأكد من حذف هذه المادة وجميع دروسها؟',
    deleteLessonConfirm: 'حذف هذا الدرس؟',
    toDoList: 'قائمة المهام', stayOrganized: 'ابقَ منظماً وتتبع تقدمك',
    totalTasks: 'إجمالي المهام', overallProgress: 'التقدم العام',
    active: 'نشطة', done: 'منجزة',
    allClear: 'لا مهام!', addFirstTaskDesc: 'أضف أول مهمة لبدء تتبع تقدمك',
    createFirstTask: 'إنشاء أول مهمة',
    addNewTask: 'إضافة مهمة جديدة', title: 'العنوان', details: 'التفاصيل',
    whatNeedsToBeDone: 'ما الذي يجب إنجازه؟', addMoreContext: 'أضف المزيد من التفاصيل...',
    priority: 'الأولوية', dueDate: 'تاريخ الاستحقاق', add: 'إضافة',
    overdueWarning: 'هذه المهمة تجاوزت موعدها النهائي!',
    signInToManageTasks: 'سجّل الدخول لإدارة مهامك',
    due: 'الموعد',
    signInToAccessSupport: 'سجّل الدخول للوصول إلى الدعم الفني',
    createAccountForHelp: 'أنشئ حساباً للحصول على مساعدة من فريقنا',
    getHelpFromTeam: 'احصل على مساعدة من فريقنا',
    newTicket: 'تذكرة جديدة', open: 'مفتوحة', resolved: 'تم حلها',
    noTicketsYet: 'لا توجد تذاكر بعد', createTicketHelp: 'أنشئ تذكرة للحصول على مساعدة من فريقنا',
    createFirstTicket: 'إنشاء أول تذكرة',
    newSupportTicket: 'تذكرة دعم جديدة',
    subjectLabel: 'الموضوع', briefIssueDesc: 'وصف مختصر لمشكلتك...',
    messageLabel: 'الرسالة', describeIssueDetail: 'صف مشكلتك بالتفصيل...',
    characters: 'حرف', creating: 'جارٍ الإنشاء...', submitTicket: 'إرسال التذكرة',
    noMessagesYetChat: 'لا توجد رسائل بعد — ابدأ المحادثة!',
    typeYourMessage: 'اكتب رسالتك...',
    signInToPractice: 'سجّل الدخول للتدريب',
    createAccountForFlashcards: 'أنشئ حساباً لاستخدام تدريب البطاقات التعليمية',
    allWords: 'الكل',
    supportDesc: 'تحتاج مساعدة؟ أنشئ تذكرة دعم وسيساعدك فريقنا.',
    codeCopied: 'تم نسخ الرمز!', yourUniqueCode: 'رمزك الفريد',
    greatJob: 'عمل رائع! أنت متألق! 🔥',
    taskCompleted: 'تم إنجاز المهمة! استمر! 💪',
    wellDone: 'أحسنت! خطوة أقرب! 🎯',
    amazing: 'مذهل! أنت تسحقها! ⭐',
    incredibleProgress: 'تقدم لا يصدق! 🚀',
    siteGuideTitle: 'دليل الموقع',
    siteGuideSubtitle: 'اكتشف جميع الميزات',
    infoHome: 'لوحة القيادة الشخصية تعرض إحصائيات الدراسة والنشاط الأخير والوصول السريع لجميع الميزات.',
    infoMaterials: 'نظّم موادك في وحدات منظمة. أضف دروساً بتنسيق نصي غني، واكتب ملاحظات مفصلة، وارفع ملفات، وصدّر كـ PDF.',
    infoVocabulary: 'ابنِ وأدِر مفرداتك. أضف كلمات مع معانٍ وملاحظات، وتدرّب بالبطاقات أو الاختبارات، وتتبع إتقانك.',
    infoPomodoro: 'حافظ على تركيزك باستخدام تقنية بومودورو. خصّص أوقات الدراسة والاستراحة واختر ألوان السمات.',
    infoMessages: 'اقرأ الإعلانات والتحديثات من المشرف. أعجب بالرسائل وشارك في الاستطلاعات.',
    infoSuggestions: 'شارك أفكارك لتحسين المنصة. أرسل طلبات ميزات وصوّت على اقتراحات الآخرين.',
    infoTodos: 'أدِر المهام بأولويات ملونة (عاجل، متوسط، منخفض). حدّد مواعيد نهائية مع عد تنازلي مباشر.',
    infoSupport: 'تحتاج مساعدة؟ أنشئ تذاكر دعم، أرفق صوراً، تحدث مع الفريق، وتتبع مشكلتك حتى حلها.',
    leaderboard: 'المتصدرون',
    leaderboardDesc: 'أفضل المتعلمين حسب النقاط',
    noLeaderboardData: 'لا توجد بيانات بعد',
    goToMessage: 'اذهب إلى الرسالة',
    pinned: 'مثبّتة',
    pause: 'إيقاف', start: 'ابدأ',
    alarmSound: 'صوت التنبيه',
    alarmChime: 'رنين', alarmBell: 'جرس', alarmDigital: 'رقمي', alarmGentle: 'هادئ', alarmNature: 'طبيعة',
    motivational1: 'ابقَ مركزاً، النجاح يُبنى لحظة بلحظة.',
    motivational2: 'إخلاصك اليوم يشكّل غدك.',
    motivational3: 'الخطوات الصغيرة تقود إلى إنجازات كبيرة.',
    motivational4: 'تقبّل العملية، وثق بالرحلة.',
    internetOutage: 'لا يوجد اتصال بالإنترنت',
    viewingAs: 'عرض كـ',
    returnToAdmin: 'العودة للإدارة',
    leaderboardHowTo: 'كيف ترتقي في الترتيب',
    leaderboardRule1Title: 'اكسب نقاط XP', leaderboardRule1Desc: 'أكمل المهام والأنشطة لكسب نقاط الخبرة.',
    leaderboardRule2Title: 'كن منتظماً', leaderboardRule2Desc: 'سجّل دخولك يومياً وأكمل جلسات الدراسة.',
    leaderboardRule3Title: 'وصول القمة', leaderboardRule3Desc: 'أفضل 3 يحصلون على تيجان ذهبية وفضية وبرونزية.',
    addLesson: 'إضافة درس', progress: 'التقدم', uploadFile: 'رفع ملف',
    selectIcon: 'اختر أيقونة', courseName: 'اسم المادة', courseNamePlaceholder: 'أدخل اسم المادة...',
  },
  fr: {
    home: 'Accueil', studyMaterials: 'Matériel d\'étude', vocabulary: 'Vocabulaire',
    createTable: 'Créer un tableau', pomodoroTimer: 'Minuteur Pomodoro',
    suggestions: 'Suggestions', messages: 'Messages', todoList: 'Liste de tâches', technicalSupport: 'Support technique',
    settings: 'Paramètres', profile: 'Profil', displayName: 'Nom d\'affichage',
    save: 'Enregistrer', avatarColor: 'Couleur de l\'avatar', avatarIcon: 'Icône de l\'avatar',
    changePassword: 'Changer le mot de passe', newPassword: 'Nouveau mot de passe...',
    confirmPassword: 'Confirmer le mot de passe...',
    appearance: 'Apparence', darkMode: 'Mode sombre', darkEnabled: 'Thème sombre activé',
    lightEnabled: 'Thème clair activé', sidebarOrder: 'Ordre de la barre latérale',
    sidebarDrag: 'Glissez-déposez pour réorganiser les boutons de navigation.',
    saveSidebarOrder: 'Enregistrer l\'ordre', account: 'Compte',
    signOutDesc: 'Déconnectez-vous de votre compte.', signOut: 'Déconnexion',
    language: 'Langue', languageDesc: 'Choisissez votre langue préférée',
    addWord: 'Ajouter un mot', practice: 'Pratiquer', difficult: 'Difficile',
    search: 'Rechercher...', masteryProgress: 'Progression de maîtrise',
    words: 'mots', mastered: 'maîtrisés', noDifficultWords: 'Pas de mots difficiles',
    noWordsFound: 'Aucun mot trouvé', noWordsYet: 'Pas encore de mots',
    greatNoDifficult: 'Super ! Aucun mot n\'est marqué comme difficile',
    tryDifferentSearch: 'Essayez un autre terme', addFirstWord: 'Ajoutez votre premier mot',
    showingDifficult: 'Affichage des mots difficiles',
    searchingFor: 'Recherche de', result: 'résultat', results: 'résultats',
    signIn: 'Connexion / Créer un compte', myProfile: 'Mon profil',
    signInBtn: 'Se connecter', createAccountBtn: 'Créer un compte',
    welcomeBack: 'Bienvenue', createYourAccount: 'Créez votre compte',
    continueYourJourney: 'Continuez votre parcours d\'apprentissage',
    startYourJourney: 'Commencez votre parcours d\'apprentissage',
    email: 'Email', password: 'Mot de passe', confirmPasswordLabel: 'Confirmer le mot de passe',
    howShouldWeCallYou: 'Comment devons-nous vous appeler ?',
    dontHaveAccount: 'Pas de compte ?', signUpLink: 'Créer un compte',
    alreadyHaveAccount: 'Déjà un compte ?', signInLink: 'Se connecter',
    backToHome: 'Retour à l\'accueil', loading: 'Chargement...',
    learnSmarter: 'Apprenez plus intelligemment',
    authFeatureDesc: 'Organisation intelligente, sessions d\'étude concentrées et outils puissants.',
    emailNotAvailable: 'Cette adresse email n\'est pas disponible',
    displayNameRequired: 'Veuillez entrer un nom d\'affichage',
    signupFailed: 'Échec de la création du compte', signinFailed: 'Échec de la connexion',
    accountCreated: 'Compte créé avec succès !', signedIn: 'Connecté avec succès !',
    signInToUse: 'Connectez-vous',
    youAreOffline: 'Hors ligne — données sauvegardées localement', hide: 'Masquer',
    changingPassword: 'Changement...',
    passwordChanged: 'Mot de passe changé', passwordsDontMatch: 'Les mots de passe ne correspondent pas',
    passwordTooShort: 'Au moins 6 caractères', displayNameUpdated: 'Nom mis à jour',
    sidebarOrderSaved: 'Ordre sauvegardé',
    testComplete: 'Test terminé !', wordsReviewed: 'mots révisés',
    easy: 'Facile', hard: 'Difficile', failed: 'Échoué', wordsToReview: 'Mots à revoir',
    testAgain: 'Refaire le test', backToVocabulary: 'Retour au vocabulaire',
    numberOfWords: 'Nombre de mots', testType: 'Type de test', testFormat: 'Format de test',
    flashcards: 'Cartes mémoire', multipleChoice: 'Choix multiple',
    flipToReveal: 'Retournez pour révéler', pickCorrect: 'Choisissez la bonne réponse',
    random: 'Aléatoire', focus: 'Concentré', smartReview: 'Révision intelligente',
    randomDesc: 'Sélection aléatoire', focusDesc: 'Mots difficiles uniquement',
    smartDesc: 'Mots nécessitant une révision', startTest: 'Commencer le test',
    byDate: 'Par date', byDateDesc: 'Quiz des mots ajoutés un jour spécifique', selectDate: 'Sélectionner une date', noDatesAvailable: 'Aucune date disponible',
    whatDoesWordMean: 'Que signifie ce mot ?', needsMorePractice: 'Besoin de plus de pratique',
    back: 'Retour',
    yourUltimate: 'Votre compagnon', studyCompanion: 'd\'étude ultime',
    homeDesc: 'Outils intelligents, organisation avancée et sessions d\'étude — tout ce dont vous avez besoin pour réussir.',
    getStartedFree: 'Commencer gratuitement', features: 'Fonctionnalités',
    everythingYouNeed: 'Tout ce dont vous avez besoin',
    readyToTransform: 'Prêt à transformer vos habitudes d\'étude ?',
    joinStudents: 'Rejoignez les étudiants qui utilisent StudyHub.',
    createFreeAccount: 'Créer un compte gratuit',
    welcomeBackUser: 'Bienvenue,',
    homeWelcomeDesc: 'StudyHub est votre boîte à outils académique complète. Organisez vos matériaux, restez concentré avec le Pomodoro et enrichissez votre vocabulaire — le tout synchronisé.',
    goToMaterials: 'Mes matériaux',
    installApp: '📱 Installez cette application pour un accès hors ligne',
    organizeMaterials: 'Organiser les matériaux', organizeMaterialsDesc: 'Gardez tout organisé en un seul endroit.',
    pomodoroTimerTitle: 'Minuteur Pomodoro', pomodoroTimerDesc: 'Restez concentré avec des sessions personnalisables.',
    vocabFlashcards: 'Vocabulaire et cartes', vocabFlashcardsDesc: 'Construisez votre vocabulaire avec des cartes mémoire.',
    signInToViewMaterials: 'Connectez-vous pour voir les matériaux',
    createAccountToSave: 'Créez un compte pour sauvegarder vos matériaux',
    addMaterial: 'Ajouter un matériau', noMaterialsYet: 'Pas encore de matériaux',
    addFirstMaterial: 'Ajoutez votre premier matériau !',
    addTask: 'Ajouter une tâche', total: 'Total', completed: 'Terminé', urgent: 'Urgent', overdue: 'En retard',
    taskTitle: 'Titre de la tâche...', taskDescription: 'Description (optionnel)',
    deadline: 'Date limite', importance: 'Importance',
    urgentLabel: 'Urgent', mediumLabel: 'Moyen', lowLabel: 'Faible',
    noTasks: 'Aucune tâche', addFirstTask: 'Ajoutez votre première tâche',
    signInForTodos: 'Connectez-vous pour les tâches',
    messagesTitle: 'Messages et sondages', noMessages: 'Aucun message',
    markAllRead: 'Tout marquer comme lu',
    suggestionsTitle: 'Suggestions', addSuggestion: 'Ajouter une suggestion',
    suggestionTitle: 'Titre', suggestionDesc: 'Description',
    noSuggestions: 'Aucune suggestion', submitSuggestion: 'Envoyer',
    study: 'Étude', shortBreak: 'Pause courte', longBreak: 'Pause longue',
    addNewWord: 'Ajouter un nouveau mot', englishWord: 'Mot en anglais', enterEnglishWord: 'Entrez le mot en anglais...',
    meaningLabel: 'Signification', enterMeaning: 'Entrez la signification...', notesOptional: 'Notes (Optionnel)',
    addNotes: 'Ajoutez des notes supplémentaires...', adding: 'Ajout...', letters: 'lettres',
    english: 'ANGLAIS', targetLanguage: 'SIGNIFICATION',
    activePolls: 'Sondages actifs', messagesSection: 'Messages',
    noMessagesDesc: 'Les messages et sondages de l\'équipe apparaîtront ici',
    thankYouVote: 'Merci pour votre contribution au développement du site ! 🎉',
    failedToVote: 'Échec du vote', adminMessage: 'Message administrateur',
    helpUsImprove: 'Aidez-nous à améliorer la plateforme',
    beFirstToShare: 'Soyez le premier à partager vos idées !',
    shareYourIdea: 'Partagez votre idée', relatedPage: 'Page associée',
    briefTitle: 'Titre bref pour votre suggestion...',
    describeInDetail: 'Décrivez votre suggestion en détail...',
    submitting: 'Envoi...', submitSuggestionBtn: 'Soumettre la suggestion',
    supported: 'Soutenu', supportThisIdea: 'Soutenir cette idée',
    accepted: 'Accepté', anonymous: 'Anonyme',
    pageGeneral: 'Général', pageMaterials: 'Matériel d\'étude', pageVocabulary: 'Vocabulaire',
    pagePomodoro: 'Minuteur Pomodoro', pageMessages: 'Messages',
    pageSettings: 'Paramètres', pageSuggestions: 'Suggestions',
    focusZone: 'Zone de concentration',
    subjects: 'matières', subject: 'matière', addCourse: 'Ajouter un cours',
    noCoursesYet: 'Pas encore de cours', addFirstCourse: 'Ajoutez votre premier cours pour commencer',
    backToMaterials: 'Retour aux matériaux', materialNotFound: 'Matériau introuvable',
    completedLessons: 'terminées', remainingLessons: 'restantes',
    lessons: 'Leçons', files: 'Fichiers', hasNotes: 'Contient des notes',
    deleteMaterialConfirm: 'Voulez-vous vraiment supprimer ce matériau et toutes ses leçons ?',
    deleteLessonConfirm: 'Supprimer cette leçon ?',
    toDoList: 'Liste de tâches', stayOrganized: 'Restez organisé et suivez votre progression',
    totalTasks: 'Total des tâches', overallProgress: 'Progression globale',
    active: 'Actives', done: 'Terminées',
    allClear: 'Tout est clair !', addFirstTaskDesc: 'Ajoutez votre première tâche pour commencer',
    createFirstTask: 'Créer la première tâche',
    addNewTask: 'Ajouter une nouvelle tâche', title: 'Titre', details: 'Détails',
    whatNeedsToBeDone: 'Que faut-il faire ?', addMoreContext: 'Ajoutez plus de contexte...',
    priority: 'Priorité', dueDate: 'Date d\'échéance', add: 'Ajouter',
    overdueWarning: 'Cette tâche a dépassé sa date limite !',
    signInToManageTasks: 'Connectez-vous pour gérer vos tâches',
    due: 'Échéance',
    signInToAccessSupport: 'Connectez-vous pour accéder au support technique',
    createAccountForHelp: 'Créez un compte pour obtenir de l\'aide de notre équipe',
    getHelpFromTeam: 'Obtenez de l\'aide de notre équipe',
    newTicket: 'Nouveau ticket', open: 'Ouvert', resolved: 'Résolu',
    noTicketsYet: 'Aucun ticket', createTicketHelp: 'Créez un ticket pour obtenir de l\'aide',
    createFirstTicket: 'Créer le premier ticket',
    newSupportTicket: 'Nouveau ticket de support',
    subjectLabel: 'Sujet', briefIssueDesc: 'Brève description de votre problème...',
    messageLabel: 'Message', describeIssueDetail: 'Décrivez votre problème en détail...',
    characters: 'caractères', creating: 'Création...', submitTicket: 'Soumettre le ticket',
    noMessagesYetChat: 'Pas encore de messages — commencez la conversation !',
    typeYourMessage: 'Tapez votre message...',
    signInToPractice: 'Connectez-vous pour pratiquer',
    createAccountForFlashcards: 'Créez un compte pour utiliser les cartes mémoire',
    allWords: 'Tous',
    supportDesc: 'Besoin d\'aide ? Créez un ticket de support et notre équipe vous assistera.',
    codeCopied: 'Code copié !', yourUniqueCode: 'Votre code unique',
    greatJob: 'Bravo ! Vous êtes en feu ! 🔥',
    taskCompleted: 'Tâche terminée ! Continuez ! 💪',
    wellDone: 'Bien joué ! Un pas de plus ! 🎯',
    amazing: 'Incroyable ! Vous écrasez tout ! ⭐',
    incredibleProgress: 'Progrès incroyable ! 🚀',
    siteGuideTitle: 'Guide du site',
    siteGuideSubtitle: 'Découvrez toutes les fonctionnalités',
    infoHome: 'Votre tableau de bord personnel avec statistiques, activité récente et accès rapide à toutes les fonctionnalités.',
    infoMaterials: 'Organisez vos cours en modules structurés. Ajoutez des leçons avec texte riche, des notes détaillées et exportez en PDF.',
    infoVocabulary: 'Construisez et gérez votre vocabulaire. Pratiquez avec des cartes mémoire ou des quiz et suivez votre maîtrise.',
    infoPomodoro: 'Restez concentré avec la technique Pomodoro. Personnalisez les durées et choisissez vos thèmes de couleur.',
    infoMessages: 'Lisez les annonces et mises à jour de l\'administrateur. Participez aux sondages et restez informé.',
    infoSuggestions: 'Partagez vos idées pour améliorer la plateforme. Soumettez des demandes et votez pour les suggestions.',
    infoTodos: 'Gérez vos tâches avec des priorités colorées. Définissez des échéances avec compte à rebours en direct.',
    infoSupport: 'Besoin d\'aide ? Créez des tickets de support, joignez des images et discutez avec l\'équipe.',
    leaderboard: 'Classement',
     leaderboardDesc: 'Meilleurs apprenants par temps passé',
     noLeaderboardData: 'Pas encore de données',
     goToMessage: 'Aller au message', pinned: 'Épinglé',
     pause: 'Pause', start: 'Démarrer',
     alarmSound: 'Son d\'alarme',
     alarmChime: 'Carillon', alarmBell: 'Cloche', alarmDigital: 'Digital', alarmGentle: 'Doux', alarmNature: 'Nature',
     motivational1: 'Restez concentré, le succès se construit moment par moment.',
     motivational2: 'Votre dévouement aujourd\'hui façonne votre demain.',
     motivational3: 'Les petits pas mènent aux grands accomplissements.',
     motivational4: 'Embrassez le processus, faites confiance au voyage.',
     internetOutage: 'Pas de connexion Internet',
     viewingAs: 'Vu en tant que', returnToAdmin: 'Retour admin',
     leaderboardHowTo: 'Comment monter en rang',
     leaderboardRule1Title: 'Gagnez des points XP', leaderboardRule1Desc: 'Complétez des tâches et activités pour gagner des points.',
     leaderboardRule2Title: 'Soyez régulier', leaderboardRule2Desc: 'Connectez-vous quotidiennement et complétez vos sessions.',
     leaderboardRule3Title: 'Atteignez le sommet', leaderboardRule3Desc: 'Les 3 meilleurs obtiennent des couronnes Or, Argent et Bronze.',
     addLesson: 'Ajouter une leçon', progress: 'Progrès', uploadFile: 'Télécharger un fichier',
     selectIcon: 'Sélectionner une icône', courseName: 'Nom du cours', courseNamePlaceholder: 'Entrez le nom du cours...',
     typing: 'Saisie', typingDesc: 'Tapez le sens de mémoire',
     typeMeaning: 'Tapez le sens', typeYourAnswer: 'Tapez votre réponse...',
     checkAnswer: 'Vérifier la réponse', correct: '✓ Correct !', incorrect: '✗ Incorrect',
     offlineMode: 'Mode hors ligne — vocabulaire en cache', offline: 'Hors ligne',
     byDate: 'Par date', byDateDesc: 'Quiz des mots ajoutés un jour spécifique', selectDate: 'Choisir une date', noDatesAvailable: 'Aucune date disponible',
   },
   zh: {
    home: '首页', studyMaterials: '学习资料', vocabulary: '词汇',
    createTable: '创建表格', pomodoroTimer: '番茄钟',
    suggestions: '建议', messages: '消息', todoList: '待办事项', technicalSupport: '技术支持',
    settings: '设置', profile: '个人资料', displayName: '显示名称',
    save: '保存', avatarColor: '头像颜色', avatarIcon: '头像图标',
    changePassword: '更改密码', newPassword: '新密码...',
    confirmPassword: '确认密码...',
    appearance: '外观', darkMode: '深色模式', darkEnabled: '深色主题已启用',
    lightEnabled: '浅色主题已启用', sidebarOrder: '侧边栏顺序',
    sidebarDrag: '拖放以重新排列导航按钮。',
    saveSidebarOrder: '保存侧边栏顺序', account: '账户',
    signOutDesc: '退出您的账户。', signOut: '退出登录',
    language: '语言', languageDesc: '选择您的首选语言',
    addWord: '添加单词', practice: '练习', difficult: '困难',
    search: '搜索...', masteryProgress: '掌握进度',
    words: '个单词', mastered: '已掌握', noDifficultWords: '没有困难单词',
    noWordsFound: '未找到单词', noWordsYet: '还没有单词',
    greatNoDifficult: '太棒了！没有标记为困难的单词',
    tryDifferentSearch: '尝试不同的搜索词', addFirstWord: '添加您的第一个单词',
    showingDifficult: '显示需要复习的困难单词',
    searchingFor: '搜索', result: '个结果', results: '个结果',
    signIn: '登录/创建账户', myProfile: '我的资料',
    signInBtn: '登录', createAccountBtn: '创建账户',
    welcomeBack: '欢迎回来', createYourAccount: '创建您的账户',
    continueYourJourney: '继续您的学习之旅',
    startYourJourney: '今天开始您的学习之旅',
    email: '邮箱', password: '密码', confirmPasswordLabel: '确认密码',
    howShouldWeCallYou: '我们怎么称呼您？',
    dontHaveAccount: '没有账户？', signUpLink: '注册',
    alreadyHaveAccount: '已有账户？', signInLink: '登录',
    backToHome: '返回首页', loading: '加载中...',
    learnSmarter: '更聪明地学习',
    authFeatureDesc: '智能工具、高效组织和专注学习——成功所需的一切。',
    emailNotAvailable: '此邮箱不可用',
    displayNameRequired: '请输入显示名称',
    signupFailed: '创建账户失败', signinFailed: '登录失败',
    accountCreated: '账户创建成功！', signedIn: '登录成功！',
    signInToUse: '登录使用',
    youAreOffline: '离线 — 数据已本地保存', hide: '隐藏',
    changingPassword: '更改中...',
    passwordChanged: '密码已更改', passwordsDontMatch: '密码不匹配',
    passwordTooShort: '至少6个字符', displayNameUpdated: '名称已更新',
    sidebarOrderSaved: '顺序已保存',
    testComplete: '测试完成！', wordsReviewed: '个单词已复习',
    easy: '简单', hard: '困难', failed: '失败', wordsToReview: '需要复习的单词',
    testAgain: '再次测试', backToVocabulary: '返回词汇',
    numberOfWords: '单词数量', testType: '测试类型', testFormat: '测试格式',
    flashcards: '闪卡', multipleChoice: '选择题',
    flipToReveal: '翻转查看含义', pickCorrect: '选择正确答案',
    random: '随机', focus: '重点', smartReview: '智能复习',
    randomDesc: '随机选择', focusDesc: '仅困难单词',
    smartDesc: '需要复习的单词', startTest: '开始测试',
    byDate: '按日期', byDateDesc: '测试特定日期添加的单词', selectDate: '选择日期', noDatesAvailable: '没有可用日期',
    whatDoesWordMean: '这个词是什么意思？', needsMorePractice: '需要更多练习',
    back: '返回',
    yourUltimate: '您的终极', studyCompanion: '学习伙伴',
    homeDesc: '智能工具、高效组织和专注学习——一站式学习平台。',
    getStartedFree: '免费开始', features: '功能',
    everythingYouNeed: '您需要的一切',
    readyToTransform: '准备好改变学习习惯了吗？',
    joinStudents: '加入使用StudyHub的学生行列。',
    createFreeAccount: '创建免费账户',
    welcomeBackUser: '欢迎回来，',
    homeWelcomeDesc: 'StudyHub是您的一站式学术工具包。整理资料、番茄钟专注学习、积累词汇——全部跨设备同步。',
    goToMaterials: '我的资料',
    installApp: '📱 安装此应用以供离线使用',
    organizeMaterials: '整理资料', organizeMaterialsDesc: '将一切整理有序，跟踪学习进度。',
    pomodoroTimerTitle: '番茄钟', pomodoroTimerDesc: '保持专注，自定义学习时段。',
    vocabFlashcards: '词汇和闪卡', vocabFlashcardsDesc: '间隔重复闪卡，建立词汇量。',
    signInToViewMaterials: '登录查看资料', createAccountToSave: '创建账户以保存和同步资料',
    addMaterial: '添加资料', noMaterialsYet: '还没有资料', addFirstMaterial: '添加第一个资料！',
    addTask: '添加任务', total: '总计', completed: '已完成', urgent: '紧急', overdue: '逾期',
    taskTitle: '任务标题...', taskDescription: '描述（可选）',
    deadline: '截止日期', importance: '重要性',
    urgentLabel: '紧急', mediumLabel: '中等', lowLabel: '低',
    noTasks: '暂无任务', addFirstTask: '添加第一个任务',
    signInForTodos: '登录使用待办事项',
    messagesTitle: '消息和投票', noMessages: '暂无消息', markAllRead: '全部标为已读',
    suggestionsTitle: '建议', addSuggestion: '添加建议',
    suggestionTitle: '标题', suggestionDesc: '描述',
    noSuggestions: '暂无建议', submitSuggestion: '提交',
    study: '学习', shortBreak: '短休息', longBreak: '长休息',
    addNewWord: '添加新单词', englishWord: '英文单词', enterEnglishWord: '输入英文单词...',
    meaningLabel: '含义', enterMeaning: '输入含义...', notesOptional: '备注（可选）',
    addNotes: '添加额外备注...', adding: '添加中...', letters: '个字母',
    english: '英文', targetLanguage: '含义',
    activePolls: '进行中的投票', messagesSection: '消息',
    noMessagesDesc: '管理员的消息和投票将显示在这里',
    thankYouVote: '感谢您为网站发展做出贡献！🎉',
    failedToVote: '投票失败', adminMessage: '管理员消息',
    helpUsImprove: '帮助我们改进平台',
    beFirstToShare: '成为第一个分享想法的人！',
    shareYourIdea: '分享您的想法', relatedPage: '相关页面',
    briefTitle: '简短标题...',
    describeInDetail: '详细描述您的建议...',
    submitting: '提交中...', submitSuggestionBtn: '提交建议',
    supported: '已支持', supportThisIdea: '支持这个想法',
    accepted: '已接受', anonymous: '匿名',
    pageGeneral: '通用', pageMaterials: '学习资料', pageVocabulary: '词汇',
    pagePomodoro: '番茄钟', pageMessages: '消息',
    pageSettings: '设置', pageSuggestions: '建议',
    focusZone: '专注区域',
    subjects: '科目', subject: '科目', addCourse: '添加课程',
    noCoursesYet: '暂无课程', addFirstCourse: '添加第一个课程开始学习',
    backToMaterials: '返回资料', materialNotFound: '资料未找到',
    completedLessons: '已完成', remainingLessons: '剩余',
    lessons: '课程', files: '文件', hasNotes: '有笔记',
    deleteMaterialConfirm: '确定要删除此资料及其所有课程吗？',
    deleteLessonConfirm: '删除此课程？',
    toDoList: '待办事项', stayOrganized: '保持有序，跟踪进度',
    totalTasks: '总任务', overallProgress: '总体进度',
    active: '进行中', done: '已完成',
    allClear: '全部完成！', addFirstTaskDesc: '添加第一个任务开始跟踪进度',
    createFirstTask: '创建第一个任务',
    addNewTask: '添加新任务', title: '标题', details: '详情',
    whatNeedsToBeDone: '需要做什么？', addMoreContext: '添加更多细节...',
    priority: '优先级', dueDate: '截止日期', add: '添加',
    overdueWarning: '此任务已超过截止日期！',
    signInToManageTasks: '登录以管理任务',
    due: '截止',
    signInToAccessSupport: '登录以访问技术支持',
    createAccountForHelp: '创建账户以获得团队帮助',
    getHelpFromTeam: '获取团队帮助',
    newTicket: '新工单', open: '打开', resolved: '已解决',
    noTicketsYet: '暂无工单', createTicketHelp: '创建工单以获取帮助',
    createFirstTicket: '创建第一个工单',
    newSupportTicket: '新支持工单',
    subjectLabel: '主题', briefIssueDesc: '简要描述您的问题...',
    messageLabel: '消息', describeIssueDetail: '详细描述您的问题...',
    characters: '字符', creating: '创建中...', submitTicket: '提交工单',
    noMessagesYetChat: '暂无消息——开始对话吧！',
    typeYourMessage: '输入您的消息...',
    signInToPractice: '登录以练习',
    createAccountForFlashcards: '创建账户以使用闪卡练习',
    allWords: '全部',
    supportDesc: '需要帮助？创建支持工单，我们的团队将为您提供帮助。',
    codeCopied: '已复制代码！', yourUniqueCode: '您的唯一代码',
    greatJob: '干得好！你太棒了！🔥', taskCompleted: '任务完成！继续加油！💪',
    wellDone: '做得好！又近一步！🎯', amazing: '太厉害了！⭐',
    incredibleProgress: '进步惊人！🚀',
    siteGuideTitle: '网站指南',
    siteGuideSubtitle: '发现所有功能',
    infoHome: '您的个人仪表板，显示学习统计、最近活动和快速访问所有功能。',
    infoMaterials: '将课程组织成结构化模块。添加富文本课程，写详细笔记，上传文件并导出为PDF。',
    infoVocabulary: '构建和管理您的词汇。添加单词、含义和笔记，用闪卡或测验练习。',
    infoPomodoro: '使用番茄工作法保持专注。自定义学习和休息时间，选择颜色主题。',
    infoMessages: '阅读管理员的公告和更新。参与投票并了解新功能。',
    infoSuggestions: '分享您的想法以改进平台。提交功能请求，为他人的建议投票。',
    infoTodos: '使用彩色优先级管理任务。设置带实时倒计时的截止日期。',
    infoSupport: '需要帮助？创建支持工单，附加图片，与团队聊天。',
    leaderboard: '排行榜',
     leaderboardDesc: '按学习时间排名',
     noLeaderboardData: '暂无数据',
     goToMessage: '前往消息', pinned: '已置顶',
     pause: '暂停', start: '开始',
     alarmSound: '闹钟声音',
     alarmChime: '铃声', alarmBell: '钟声', alarmDigital: '电子', alarmGentle: '柔和', alarmNature: '自然',
     motivational1: '保持专注，成功是一点一滴积累的。', motivational2: '你今天的努力塑造你的明天。',
     motivational3: '小步骤通向大成就。', motivational4: '享受过程，相信旅程。',
     internetOutage: '无网络连接',
     viewingAs: '查看身份', returnToAdmin: '返回管理',
     leaderboardHowTo: '如何提升排名',
     leaderboardRule1Title: '赚取XP积分', leaderboardRule1Desc: '完成任务和活动以赚取经验值。',
     leaderboardRule2Title: '保持坚持', leaderboardRule2Desc: '每日登录并完成学习课程。',
     leaderboardRule3Title: '到达顶峰', leaderboardRule3Desc: '前3名获得金、银、铜冠。',
     addLesson: '添加课程', progress: '进度', uploadFile: '上传文件',
     selectIcon: '选择图标', courseName: '课程名称', courseNamePlaceholder: '输入课程名称...',
     typing: '打字', typingDesc: '从记忆中输入含义', typeMeaning: '输入含义', typeYourAnswer: '输入你的答案...',
     checkAnswer: '检查答案', correct: '✓ 正确！', incorrect: '✗ 错误',
     offlineMode: '离线模式 — 使用缓存词汇', offline: '离线',
   },
   ja: {
     home: 'ホーム', studyMaterials: '学習資料', vocabulary: '語彙',
    createTable: 'テーブル作成', pomodoroTimer: 'ポモドーロ',
    suggestions: '提案', messages: 'メッセージ', todoList: 'やることリスト', technicalSupport: 'テクニカルサポート',
    settings: '設定', profile: 'プロフィール', displayName: '表示名',
    save: '保存', avatarColor: 'アバターの色', avatarIcon: 'アバターアイコン',
    changePassword: 'パスワード変更', newPassword: '新しいパスワード...',
    confirmPassword: 'パスワード確認...',
    appearance: '外観', darkMode: 'ダークモード', darkEnabled: 'ダークテーマ有効',
    lightEnabled: 'ライトテーマ有効', sidebarOrder: 'サイドバー順序',
    sidebarDrag: 'ドラッグ＆ドロップで並べ替え。',
    saveSidebarOrder: '順序を保存', account: 'アカウント',
    signOutDesc: 'このデバイスからサインアウト。', signOut: 'サインアウト',
    language: '言語', languageDesc: 'お好みの言語を選択',
    addWord: '単語追加', practice: '練習', difficult: '難しい',
    search: '検索...', masteryProgress: '習得進捗',
    words: '語', mastered: '習得済み', noDifficultWords: '難しい単語なし',
    noWordsFound: '単語が見つかりません', noWordsYet: 'まだ単語がありません',
    greatNoDifficult: '素晴らしい！難しい単語はありません',
    tryDifferentSearch: '別の検索語を試してください', addFirstWord: '最初の単語を追加',
    showingDifficult: '復習が必要な難しい単語を表示',
    searchingFor: '検索中', result: '件', results: '件',
    signIn: 'ログイン/アカウント作成', myProfile: 'マイプロフィール',
    signInBtn: 'ログイン', createAccountBtn: 'アカウント作成',
    welcomeBack: 'おかえりなさい', createYourAccount: 'アカウント作成',
    continueYourJourney: '学習を続けましょう',
    startYourJourney: '今日から学習を始めましょう',
    email: 'メール', password: 'パスワード', confirmPasswordLabel: 'パスワード確認',
    howShouldWeCallYou: 'お名前は？',
    dontHaveAccount: 'アカウントがない？', signUpLink: '登録',
    alreadyHaveAccount: 'アカウントがある？', signInLink: 'ログイン',
    backToHome: 'ホームに戻る', loading: '読み込み中...',
    learnSmarter: 'もっと賢く学ぼう',
    authFeatureDesc: 'スマートな整理、集中学習セッション、強力なツール。',
    emailNotAvailable: 'このメールアドレスは使用できません',
    displayNameRequired: '表示名を入力してください',
    signupFailed: 'アカウント作成に失敗', signinFailed: 'ログインに失敗',
    accountCreated: 'アカウント作成成功！', signedIn: 'ログイン成功！',
    signInToUse: 'ログインして使用',
    youAreOffline: 'オフライン — データはローカルに保存', hide: '非表示',
    changingPassword: '変更中...',
    passwordChanged: 'パスワード変更済み', passwordsDontMatch: 'パスワードが一致しません',
    passwordTooShort: '6文字以上必要', displayNameUpdated: '名前更新済み',
    sidebarOrderSaved: '順序保存済み',
    testComplete: 'テスト完了！', wordsReviewed: '語復習済み',
    easy: '簡単', hard: '難しい', failed: '不合格', wordsToReview: '復習する単語',
    testAgain: '再テスト', backToVocabulary: '語彙に戻る',
    numberOfWords: '単語数', testType: 'テストタイプ', testFormat: 'テスト形式',
    flashcards: 'フラッシュカード', multipleChoice: '選択問題',
    flipToReveal: 'めくって確認', pickCorrect: '正解を選択',
    random: 'ランダム', focus: '集中', smartReview: 'スマート復習',
    randomDesc: 'ランダム選択', focusDesc: '難しい単語のみ',
    smartDesc: '復習が必要な単語', startTest: 'テスト開始',
    byDate: '日付別', byDateDesc: '特定の日に追加された単語をテスト', selectDate: '日付を選択', noDatesAvailable: '利用可能な日付がありません',
    whatDoesWordMean: 'この単語の意味は？', needsMorePractice: 'もっと練習が必要',
    back: '戻る',
    yourUltimate: '究極の', studyCompanion: '学習パートナー',
    homeDesc: 'スマートツール、効率的な整理、集中学習セッション——すべてが一か所に。',
    getStartedFree: '無料で始める', features: '機能',
    everythingYouNeed: '成功に必要なすべて',
    readyToTransform: '学習習慣を変える準備はできましたか？',
    joinStudents: 'StudyHubを使う学生に参加しましょう。',
    createFreeAccount: '無料アカウントを作成',
    welcomeBackUser: 'おかえりなさい、',
    homeWelcomeDesc: 'StudyHubはあなたの学術ツールキットです。資料整理、ポモドーロ、語彙強化——すべて同期。',
    goToMaterials: '資料へ',
    installApp: '📱 オフラインアクセスのためにアプリをインストール',
    organizeMaterials: '資料整理', organizeMaterialsDesc: 'すべてを一か所に整理。',
    pomodoroTimerTitle: 'ポモドーロ', pomodoroTimerDesc: 'カスタマイズ可能な学習セッション。',
    vocabFlashcards: '語彙とフラッシュカード', vocabFlashcardsDesc: '間隔反復で語彙力を強化。',
    signInToViewMaterials: 'ログインして資料を表示', createAccountToSave: 'アカウントを作成して保存',
    addMaterial: '資料追加', noMaterialsYet: 'まだ資料がありません', addFirstMaterial: '最初の資料を追加！',
    addTask: 'タスク追加', total: '合計', completed: '完了', urgent: '緊急', overdue: '期限切れ',
    taskTitle: 'タスク名...', taskDescription: '説明（任意）',
    deadline: '期限', importance: '重要度',
    urgentLabel: '緊急', mediumLabel: '中', lowLabel: '低',
    noTasks: 'タスクなし', addFirstTask: '最初のタスクを追加',
    signInForTodos: 'ログインしてタスク管理',
    messagesTitle: 'メッセージと投票', noMessages: 'メッセージなし', markAllRead: 'すべて既読',
    suggestionsTitle: '提案', addSuggestion: '提案を追加',
    suggestionTitle: 'タイトル', suggestionDesc: '説明',
    noSuggestions: '提案なし', submitSuggestion: '送信',
    study: '学習', shortBreak: '短い休憩', longBreak: '長い休憩',
    addNewWord: '新しい単語を追加', englishWord: '英語の単語', enterEnglishWord: '英語の単語を入力...',
    meaningLabel: '意味', enterMeaning: '意味を入力...', notesOptional: 'メモ（任意）',
    addNotes: '追加メモを入力...', adding: '追加中...', letters: '文字',
    english: '英語', targetLanguage: '意味',
    activePolls: 'アクティブな投票', messagesSection: 'メッセージ',
    noMessagesDesc: '管理チームからのメッセージと投票がここに表示されます',
    thankYouVote: 'サイトの発展への貢献ありがとうございます！🎉',
    failedToVote: '投票に失敗', adminMessage: '管理者メッセージ',
    helpUsImprove: 'プラットフォームの改善にご協力ください',
    beFirstToShare: '最初にアイデアを共有しましょう！',
    shareYourIdea: 'アイデアを共有', relatedPage: '関連ページ',
    briefTitle: '提案の簡単なタイトル...',
    describeInDetail: '提案を詳しく説明してください...',
    submitting: '送信中...', submitSuggestionBtn: '提案を送信',
    supported: 'サポート済み', supportThisIdea: 'このアイデアをサポート',
    accepted: '承認済み', anonymous: '匿名',
    pageGeneral: '一般', pageMaterials: '学習資料', pageVocabulary: '語彙',
    pagePomodoro: 'ポモドーロ', pageMessages: 'メッセージ',
    pageSettings: '設定', pageSuggestions: '提案',
    focusZone: '集中ゾーン',
    subjects: '科目', subject: '科目', addCourse: 'コースを追加',
    noCoursesYet: 'まだコースがありません', addFirstCourse: '最初のコースを追加して始めましょう',
    backToMaterials: '資料に戻る', materialNotFound: '資料が見つかりません',
    completedLessons: '完了', remainingLessons: '残り',
    lessons: 'レッスン', files: 'ファイル', hasNotes: 'メモあり',
    deleteMaterialConfirm: 'この資料とすべてのレッスンを削除しますか？',
    deleteLessonConfirm: 'このレッスンを削除しますか？',
    toDoList: 'やることリスト', stayOrganized: '整理して進捗を追跡',
    totalTasks: '合計タスク', overallProgress: '全体の進捗',
    active: 'アクティブ', done: '完了',
    allClear: 'すべてクリア！', addFirstTaskDesc: '最初のタスクを追加して進捗を追跡',
    createFirstTask: '最初のタスクを作成',
    addNewTask: '新しいタスクを追加', title: 'タイトル', details: '詳細',
    whatNeedsToBeDone: '何をする必要がありますか？', addMoreContext: '詳細を追加...',
    priority: '優先度', dueDate: '期日', add: '追加',
    overdueWarning: 'このタスクは期限を過ぎています！',
    signInToManageTasks: 'ログインしてタスクを管理',
    due: '期限',
    signInToAccessSupport: 'ログインしてテクニカルサポートにアクセス',
    createAccountForHelp: 'アカウントを作成してサポートを受ける',
    getHelpFromTeam: 'チームからサポートを受ける',
    newTicket: '新しいチケット', open: '未解決', resolved: '解決済み',
    noTicketsYet: 'チケットなし', createTicketHelp: 'チケットを作成してサポートを受ける',
    createFirstTicket: '最初のチケットを作成',
    newSupportTicket: '新しいサポートチケット',
    subjectLabel: '件名', briefIssueDesc: '問題の簡単な説明...',
    messageLabel: 'メッセージ', describeIssueDetail: '問題を詳しく説明してください...',
    characters: '文字', creating: '作成中...', submitTicket: 'チケットを送信',
    noMessagesYetChat: 'まだメッセージがありません — 会話を始めましょう！',
    typeYourMessage: 'メッセージを入力...',
    signInToPractice: 'ログインして練習',
    createAccountForFlashcards: 'アカウントを作成してフラッシュカード練習を利用',
    allWords: 'すべて',
    supportDesc: 'お困りですか？サポートチケットを作成してください。',
    codeCopied: 'コードがコピーされました！', yourUniqueCode: 'あなたの固有コード',
    greatJob: 'すごい！絶好調！🔥', taskCompleted: 'タスク完了！続けよう！💪',
    wellDone: 'よくできました！🎯', amazing: '素晴らしい！⭐',
    incredibleProgress: '驚異的な進歩！🚀',
    siteGuideTitle: 'サイトガイド',
    siteGuideSubtitle: 'すべての機能を発見',
    infoHome: '学習統計、最近のアクティビティ、すべての機能への素早いアクセスを表示するダッシュボード。',
    infoMaterials: 'コースを構造化されたモジュールに整理。リッチテキストでレッスンを追加し、PDFでエクスポート。',
    infoVocabulary: '語彙を構築・管理。フラッシュカードやクイズで練習し、間隔反復で習得を追跡。',
    infoPomodoro: 'ポモドーロテクニックで集中。学習と休憩の時間をカスタマイズ。',
    infoMessages: '管理者からのお知らせと更新を読む。投票に参加して新機能を知る。',
    infoSuggestions: 'プラットフォーム改善のアイデアを共有。機能リクエストを送信し、他の提案に投票。',
    infoTodos: '色分け優先度でタスクを管理。リアルタイムカウントダウン付きの期限を設定。',
    infoSupport: 'お困りですか？サポートチケットを作成し、画像を添付してチームとチャット。',
    leaderboard: 'ランキング',
     leaderboardDesc: '学習時間によるトップ',
     noLeaderboardData: 'データなし',
     goToMessage: 'メッセージへ', pinned: 'ピン留め',
     pause: '一時停止', start: 'スタート',
     alarmSound: 'アラーム音',
     alarmChime: 'チャイム', alarmBell: 'ベル', alarmDigital: 'デジタル', alarmGentle: '優しい', alarmNature: '自然',
     motivational1: '集中を続けて、成功は一瞬一瞬の積み重ねです。', motivational2: '今日の努力が明日を形作ります。',
     motivational3: '小さな一歩が大きな成果に繋がります。', motivational4: 'プロセスを楽しみ、旅を信じましょう。',
     internetOutage: 'インターネット接続なし',
     viewingAs: '表示中', returnToAdmin: '管理に戻る',
     leaderboardHowTo: 'ランクアップの方法',
     leaderboardRule1Title: 'XPポイントを獲得', leaderboardRule1Desc: 'タスクとアクティビティを完了してXPを獲得。',
     leaderboardRule2Title: '一貫性を保つ', leaderboardRule2Desc: '毎日ログインして学習セッションを完了。',
     leaderboardRule3Title: 'トップを目指す', leaderboardRule3Desc: 'トップ3は金・銀・銅の王冠を獲得。',
     addLesson: 'レッスンを追加', progress: '進捗', uploadFile: 'ファイルをアップロード',
     selectIcon: 'アイコンを選択', courseName: 'コース名', courseNamePlaceholder: 'コース名を入力...',
     typing: 'タイピング', typingDesc: '記憶から意味を入力', typeMeaning: '意味を入力', typeYourAnswer: '答えを入力...',
     checkAnswer: '答えを確認', correct: '✓ 正解！', incorrect: '✗ 不正解',
     offlineMode: 'オフラインモード — キャッシュされた語彙を使用', offline: 'オフライン',
   },
   hi: {
     home: 'होम', studyMaterials: 'अध्ययन सामग्री', vocabulary: 'शब्दावली',
    createTable: 'तालिका बनाएं', pomodoroTimer: 'पोमोडोरो टाइमर',
    suggestions: 'सुझाव', messages: 'संदेश', todoList: 'कार्य सूची', technicalSupport: 'तकनीकी सहायता',
    settings: 'सेटिंग्स', profile: 'प्रोफ़ाइल', displayName: 'प्रदर्शन नाम',
    save: 'सहेजें', avatarColor: 'अवतार रंग', avatarIcon: 'अवतार आइकन',
    changePassword: 'पासवर्ड बदलें', newPassword: 'नया पासवर्ड...',
    confirmPassword: 'पासवर्ड की पुष्टि...',
    appearance: 'दिखावट', darkMode: 'डार्क मोड', darkEnabled: 'डार्क थीम सक्रिय',
    lightEnabled: 'लाइट थीम सक्रिय', sidebarOrder: 'साइडबार क्रम',
    sidebarDrag: 'नेविगेशन बटन पुनर्व्यवस्थित करने के लिए ड्रैग और ड्रॉप करें।',
    saveSidebarOrder: 'साइडबार क्रम सहेजें', account: 'खाता',
    signOutDesc: 'इस डिवाइस से साइन आउट करें।', signOut: 'साइन आउट',
    language: 'भाषा', languageDesc: 'अपनी पसंदीदा भाषा चुनें',
    addWord: 'शब्द जोड़ें', practice: 'अभ्यास', difficult: 'कठिन',
    search: 'खोजें...', masteryProgress: 'महारत प्रगति',
    words: 'शब्द', mastered: 'महारत हासिल', noDifficultWords: 'कोई कठिन शब्द नहीं',
    noWordsFound: 'कोई शब्द नहीं मिला', noWordsYet: 'अभी तक कोई शब्द नहीं',
    greatNoDifficult: 'बढ़िया! कोई कठिन शब्द नहीं',
    tryDifferentSearch: 'कोई और खोज शब्द आज़माएं', addFirstWord: 'अपना पहला शब्द जोड़ें',
    showingDifficult: 'कठिन शब्द दिखा रहे हैं',
    searchingFor: 'खोज रहे हैं', result: 'परिणाम', results: 'परिणाम',
    signIn: 'साइन इन / खाता बनाएं', myProfile: 'मेरा प्रोफ़ाइल',
    signInBtn: 'साइन इन', createAccountBtn: 'खाता बनाएं',
    welcomeBack: 'वापसी पर स्वागत', createYourAccount: 'अपना खाता बनाएं',
    continueYourJourney: 'अपनी सीखने की यात्रा जारी रखें',
    startYourJourney: 'आज अपनी सीखने की यात्रा शुरू करें',
    email: 'ईमेल', password: 'पासवर्ड', confirmPasswordLabel: 'पासवर्ड की पुष्टि',
    howShouldWeCallYou: 'हम आपको क्या बुलाएं?',
    dontHaveAccount: 'खाता नहीं है?', signUpLink: 'साइन अप',
    alreadyHaveAccount: 'पहले से खाता है?', signInLink: 'साइन इन',
    backToHome: 'होम पर वापस', loading: 'लोड हो रहा...',
    learnSmarter: 'चतुराई से सीखें',
    authFeatureDesc: 'स्मार्ट संगठन, केंद्रित अध्ययन सत्र और शक्तिशाली उपकरण।',
    emailNotAvailable: 'यह ईमेल उपलब्ध नहीं है',
    displayNameRequired: 'कृपया प्रदर्शन नाम दर्ज करें',
    signupFailed: 'खाता बनाने में विफल', signinFailed: 'साइन इन विफल',
    accountCreated: 'खाता सफलतापूर्वक बनाया गया!', signedIn: 'सफलतापूर्वक साइन इन!',
    signInToUse: 'उपयोग करने के लिए साइन इन करें',
    youAreOffline: 'ऑफ़लाइन — डेटा स्थानीय रूप से सहेजा गया', hide: 'छिपाएं',
    changingPassword: 'बदल रहा...',
    passwordChanged: 'पासवर्ड बदला गया', passwordsDontMatch: 'पासवर्ड मेल नहीं खाते',
    passwordTooShort: 'कम से कम 6 अक्षर', displayNameUpdated: 'नाम अपडेट किया गया',
    sidebarOrderSaved: 'क्रम सहेजा गया',
    testComplete: 'परीक्षा पूर्ण!', wordsReviewed: 'शब्दों की समीक्षा',
    easy: 'आसान', hard: 'कठिन', failed: 'असफल', wordsToReview: 'समीक्षा के लिए शब्द',
    testAgain: 'फिर से परीक्षा', backToVocabulary: 'शब्दावली पर वापस',
    numberOfWords: 'शब्दों की संख्या', testType: 'परीक्षा प्रकार', testFormat: 'परीक्षा प्रारूप',
    flashcards: 'फ्लैशकार्ड', multipleChoice: 'बहुविकल्पी',
    flipToReveal: 'अर्थ देखने के लिए पलटें', pickCorrect: 'सही उत्तर चुनें',
    random: 'यादृच्छिक', focus: 'केंद्रित', smartReview: 'स्मार्ट समीक्षा',
    randomDesc: 'यादृच्छिक चयन', focusDesc: 'केवल कठिन शब्द',
    byDate: 'तारीख के अनुसार', byDateDesc: 'किसी विशिष्ट दिन जोड़े गए शब्दों का क्विज़', selectDate: 'तारीख चुनें', noDatesAvailable: 'कोई तारीख उपलब्ध नहीं',
    smartDesc: 'समीक्षा की आवश्यकता वाले शब्द', startTest: 'परीक्षा शुरू',
    whatDoesWordMean: 'इस शब्द का अर्थ?', needsMorePractice: 'और अभ्यास चाहिए',
    back: 'वापस',
    yourUltimate: 'आपका सर्वोत्तम', studyCompanion: 'अध्ययन साथी',
    homeDesc: 'स्मार्ट उपकरण, कुशल संगठन और अध्ययन सत्र — सब कुछ एक जगह।',
    getStartedFree: 'मुफ्त में शुरू करें', features: 'सुविधाएं',
    everythingYouNeed: 'सफलता के लिए सब कुछ',
    readyToTransform: 'अपनी अध्ययन आदतें बदलने के लिए तैयार?',
    joinStudents: 'StudyHub का उपयोग करने वाले छात्रों से जुड़ें।',
    createFreeAccount: 'मुफ्त खाता बनाएं',
    welcomeBackUser: 'वापसी पर स्वागत,',
    homeWelcomeDesc: 'StudyHub आपका ऑल-इन-वन अकादमिक टूलकिट है। सामग्री व्यवस्थित करें, पोमोडोरो से ध्यान केंद्रित रखें, शब्दावली बनाएं — सब कुछ सिंक।',
    goToMaterials: 'मेरी सामग्री',
    installApp: '📱 ऑफ़लाइन एक्सेस के लिए ऐप इंस्टॉल करें',
    organizeMaterials: 'सामग्री व्यवस्थित करें', organizeMaterialsDesc: 'सब कुछ एक जगह व्यवस्थित रखें।',
    pomodoroTimerTitle: 'पोमोडोरो टाइमर', pomodoroTimerDesc: 'अनुकूलन योग्य सत्रों से ध्यान केंद्रित रखें।',
    vocabFlashcards: 'शब्दावली और कार्ड', vocabFlashcardsDesc: 'स्पेस्ड रिपीटिशन से शब्दावली बनाएं।',
    signInToViewMaterials: 'सामग्री देखने के लिए साइन इन', createAccountToSave: 'सहेजने और सिंक करने के लिए खाता बनाएं',
    addMaterial: 'सामग्री जोड़ें', noMaterialsYet: 'अभी कोई सामग्री नहीं', addFirstMaterial: 'पहली सामग्री जोड़ें!',
    addTask: 'कार्य जोड़ें', total: 'कुल', completed: 'पूर्ण', urgent: 'जरूरी', overdue: 'विलंबित',
    taskTitle: 'कार्य शीर्षक...', taskDescription: 'विवरण (वैकल्पिक)',
    deadline: 'समय सीमा', importance: 'महत्व',
    urgentLabel: 'जरूरी', mediumLabel: 'मध्यम', lowLabel: 'कम',
    noTasks: 'कोई कार्य नहीं', addFirstTask: 'पहला कार्य जोड़ें',
    signInForTodos: 'कार्य सूची के लिए साइन इन',
    messagesTitle: 'संदेश और मतदान', noMessages: 'कोई संदेश नहीं', markAllRead: 'सब पढ़ा हुआ',
    suggestionsTitle: 'सुझाव', addSuggestion: 'सुझाव जोड़ें',
    suggestionTitle: 'शीर्षक', suggestionDesc: 'विवरण',
    noSuggestions: 'कोई सुझाव नहीं', submitSuggestion: 'भेजें',
    study: 'अध्ययन', shortBreak: 'छोटा ब्रेक', longBreak: 'लंबा ब्रेक',
    addNewWord: 'नया शब्द जोड़ें', englishWord: 'अंग्रेजी शब्द', enterEnglishWord: 'अंग्रेजी शब्द दर्ज करें...',
    meaningLabel: 'अर्थ', enterMeaning: 'अर्थ दर्ज करें...', notesOptional: 'नोट्स (वैकल्पिक)',
    addNotes: 'अतिरिक्त नोट्स जोड़ें...', adding: 'जोड़ रहा...', letters: 'अक्षर',
    english: 'अंग्रेजी', targetLanguage: 'अर्थ',
    activePolls: 'सक्रिय मतदान', messagesSection: 'संदेश',
    noMessagesDesc: 'प्रशासन टीम के संदेश और मतदान यहां दिखेंगे',
    thankYouVote: 'साइट के विकास में योगदान के लिए धन्यवाद! 🎉',
    failedToVote: 'वोट करने में विफल', adminMessage: 'प्रशासक संदेश',
    helpUsImprove: 'प्लेटफॉर्म को बेहतर बनाने में मदद करें',
    beFirstToShare: 'अपने विचार साझा करने वाले पहले बनें!',
    shareYourIdea: 'अपना विचार साझा करें', relatedPage: 'संबंधित पृष्ठ',
    briefTitle: 'अपने सुझाव का संक्षिप्त शीर्षक...',
    describeInDetail: 'अपने सुझाव का विस्तार से वर्णन करें...',
    submitting: 'भेज रहा...', submitSuggestionBtn: 'सुझाव भेजें',
    supported: 'समर्थित', supportThisIdea: 'इस विचार का समर्थन करें',
    accepted: 'स्वीकृत', anonymous: 'अनाम',
    pageGeneral: 'सामान्य', pageMaterials: 'अध्ययन सामग्री', pageVocabulary: 'शब्दावली',
    pagePomodoro: 'पोमोडोरो टाइमर', pageMessages: 'संदेश',
    pageSettings: 'सेटिंग्स', pageSuggestions: 'सुझाव',
    focusZone: 'ध्यान केंद्रित क्षेत्र',
    subjects: 'विषय', subject: 'विषय', addCourse: 'कोर्स जोड़ें',
    noCoursesYet: 'अभी कोई कोर्स नहीं', addFirstCourse: 'शुरू करने के लिए पहला कोर्स जोड़ें',
    backToMaterials: 'सामग्री पर वापस', materialNotFound: 'सामग्री नहीं मिली',
    completedLessons: 'पूर्ण', remainingLessons: 'शेष',
    lessons: 'पाठ', files: 'फ़ाइलें', hasNotes: 'नोट्स हैं',
    deleteMaterialConfirm: 'क्या आप इस सामग्री और सभी पाठों को हटाना चाहते हैं?',
    deleteLessonConfirm: 'यह पाठ हटाएं?',
    toDoList: 'कार्य सूची', stayOrganized: 'व्यवस्थित रहें और अपनी प्रगति ट्रैक करें',
    totalTasks: 'कुल कार्य', overallProgress: 'समग्र प्रगति',
    active: 'सक्रिय', done: 'पूर्ण',
    allClear: 'सब साफ!', addFirstTaskDesc: 'प्रगति ट्रैक करने के लिए पहला कार्य जोड़ें',
    createFirstTask: 'पहला कार्य बनाएं',
    addNewTask: 'नया कार्य जोड़ें', title: 'शीर्षक', details: 'विवरण',
    whatNeedsToBeDone: 'क्या करना है?', addMoreContext: 'और विवरण जोड़ें...',
    priority: 'प्राथमिकता', dueDate: 'नियत तिथि', add: 'जोड़ें',
    overdueWarning: 'यह कार्य अपनी समय सीमा पार कर चुका है!',
    signInToManageTasks: 'कार्य प्रबंधित करने के लिए साइन इन करें',
    due: 'नियत',
    signInToAccessSupport: 'तकनीकी सहायता के लिए साइन इन करें',
    createAccountForHelp: 'हमारी टीम से मदद पाने के लिए खाता बनाएं',
    getHelpFromTeam: 'हमारी टीम से मदद पाएं',
    newTicket: 'नया टिकट', open: 'खुला', resolved: 'हल किया गया',
    noTicketsYet: 'कोई टिकट नहीं', createTicketHelp: 'मदद पाने के लिए टिकट बनाएं',
    createFirstTicket: 'पहला टिकट बनाएं',
    newSupportTicket: 'नया सहायता टिकट',
    subjectLabel: 'विषय', briefIssueDesc: 'अपनी समस्या का संक्षिप्त विवरण...',
    messageLabel: 'संदेश', describeIssueDetail: 'अपनी समस्या का विस्तार से वर्णन करें...',
    characters: 'अक्षर', creating: 'बना रहा...', submitTicket: 'टिकट भेजें',
    noMessagesYetChat: 'अभी कोई संदेश नहीं — बातचीत शुरू करें!',
    typeYourMessage: 'अपना संदेश लिखें...',
    signInToPractice: 'अभ्यास के लिए साइन इन करें',
    createAccountForFlashcards: 'फ्लैशकार्ड अभ्यास के लिए खाता बनाएं',
    allWords: 'सभी',
    supportDesc: 'मदद चाहिए? सहायता टिकट बनाएं और हमारी टीम आपकी मदद करेगी।',
    codeCopied: 'कोड कॉपी हो गया!', yourUniqueCode: 'आपका अनोखा कोड',
    greatJob: 'शानदार! आप बेहतरीन कर रहे हैं! 🔥', taskCompleted: 'कार्य पूर्ण! जारी रखें! 💪',
    wellDone: 'बहुत बढ़िया! एक कदम और करीब! 🎯', amazing: 'अद्भुत! ⭐',
    incredibleProgress: 'अविश्वसनीय प्रगति! 🚀',
    siteGuideTitle: 'साइट गाइड',
    siteGuideSubtitle: 'सभी सुविधाएं खोजें',
    infoHome: 'आपका व्यक्तिगत डैशबोर्ड जो अध्ययन आँकड़े, हाल की गतिविधि और सभी सुविधाओं तक त्वरित पहुँच दिखाता है।',
    infoMaterials: 'अपने पाठ्यक्रमों को संरचित मॉड्यूल में व्यवस्थित करें। रिच टेक्स्ट में पाठ जोड़ें और PDF में निर्यात करें।',
    infoVocabulary: 'अपनी शब्दावली बनाएं और प्रबंधित करें। फ्लैशकार्ड या क्विज़ से अभ्यास करें।',
    infoPomodoro: 'पोमोडोरो तकनीक से ध्यान केंद्रित रखें। अध्ययन और विश्राम की अवधि अनुकूलित करें।',
    infoMessages: 'प्रशासक से घोषणाएं और अपडेट पढ़ें। मतदान में भाग लें।',
    infoSuggestions: 'प्लेटफॉर्म को बेहतर बनाने के लिए अपने विचार साझा करें। सुविधा अनुरोध भेजें और दूसरों के सुझावों पर वोट करें।',
    infoTodos: 'रंग-कोडित प्राथमिकताओं के साथ कार्य प्रबंधित करें। लाइव काउंटडाउन के साथ समय सीमा निर्धारित करें।',
    infoSupport: 'मदद चाहिए? सहायता टिकट बनाएं, छवियां संलग्न करें और टीम से चैट करें।',
    leaderboard: 'लीडरबोर्ड',
    leaderboardDesc: 'समय के अनुसार शीर्ष शिक्षार्थी',
    noLeaderboardData: 'अभी कोई डेटा नहीं',
  },
  es: {
    home: 'Inicio', studyMaterials: 'Material de estudio', vocabulary: 'Vocabulario',
    createTable: 'Crear tabla', pomodoroTimer: 'Temporizador Pomodoro',
    suggestions: 'Sugerencias', messages: 'Mensajes', todoList: 'Lista de tareas', technicalSupport: 'Soporte técnico',
    settings: 'Configuración', profile: 'Perfil', displayName: 'Nombre visible',
    save: 'Guardar', avatarColor: 'Color de avatar', avatarIcon: 'Ícono de avatar',
    changePassword: 'Cambiar contraseña', newPassword: 'Nueva contraseña...',
    confirmPassword: 'Confirmar contraseña...',
    appearance: 'Apariencia', darkMode: 'Modo oscuro', darkEnabled: 'Tema oscuro activado',
    lightEnabled: 'Tema claro activado', sidebarOrder: 'Orden de la barra lateral',
    sidebarDrag: 'Arrastra para reordenar los botones de navegación.',
    saveSidebarOrder: 'Guardar orden', account: 'Cuenta',
    signOutDesc: 'Cerrar sesión en este dispositivo.', signOut: 'Cerrar sesión',
    language: 'Idioma', languageDesc: 'Elige tu idioma preferido',
    addWord: 'Agregar palabra', practice: 'Practicar', difficult: 'Difícil',
    search: 'Buscar...', masteryProgress: 'Progreso de dominio',
    words: 'palabras', mastered: 'dominadas', noDifficultWords: 'Sin palabras difíciles',
    noWordsFound: 'No se encontraron palabras', noWordsYet: 'Aún no hay palabras',
    greatNoDifficult: '¡Genial! No hay palabras difíciles',
    tryDifferentSearch: 'Intenta otro término', addFirstWord: 'Agrega tu primera palabra',
    showingDifficult: 'Mostrando palabras difíciles',
    searchingFor: 'Buscando', result: 'resultado', results: 'resultados',
    signIn: 'Iniciar sesión / Crear cuenta', myProfile: 'Mi perfil',
    signInBtn: 'Iniciar sesión', createAccountBtn: 'Crear cuenta',
    welcomeBack: 'Bienvenido de vuelta', createYourAccount: 'Crea tu cuenta',
    continueYourJourney: 'Continúa tu camino de aprendizaje',
    startYourJourney: 'Comienza tu camino de aprendizaje hoy',
    email: 'Email', password: 'Contraseña', confirmPasswordLabel: 'Confirmar contraseña',
    howShouldWeCallYou: '¿Cómo debemos llamarte?',
    dontHaveAccount: '¿No tienes cuenta?', signUpLink: 'Regístrate',
    alreadyHaveAccount: '¿Ya tienes cuenta?', signInLink: 'Inicia sesión',
    backToHome: 'Volver al inicio', loading: 'Cargando...',
    learnSmarter: 'Aprende más inteligentemente',
    authFeatureDesc: 'Organización inteligente, sesiones de estudio enfocadas y herramientas poderosas.',
    emailNotAvailable: 'Este correo no está disponible',
    displayNameRequired: 'Por favor ingresa un nombre',
    signupFailed: 'Error al crear la cuenta', signinFailed: 'Error al iniciar sesión',
    accountCreated: '¡Cuenta creada exitosamente!', signedIn: '¡Sesión iniciada!',
    signInToUse: 'Inicia sesión',
    youAreOffline: 'Sin conexión — datos guardados localmente', hide: 'Ocultar',
    changingPassword: 'Cambiando...',
    passwordChanged: 'Contraseña cambiada', passwordsDontMatch: 'Las contraseñas no coinciden',
    passwordTooShort: 'Mínimo 6 caracteres', displayNameUpdated: 'Nombre actualizado',
    sidebarOrderSaved: 'Orden guardado',
    testComplete: '¡Prueba completa!', wordsReviewed: 'palabras revisadas',
    easy: 'Fácil', hard: 'Difícil', failed: 'Fallido', wordsToReview: 'Palabras a repasar',
    testAgain: 'Repetir prueba', backToVocabulary: 'Volver al vocabulario',
    numberOfWords: 'Número de palabras', testType: 'Tipo de prueba', testFormat: 'Formato de prueba',
    flashcards: 'Tarjetas', multipleChoice: 'Opción múltiple',
    flipToReveal: 'Voltea para revelar', pickCorrect: 'Elige la respuesta correcta',
    random: 'Aleatorio', focus: 'Enfocado', smartReview: 'Repaso inteligente',
    randomDesc: 'Selección aleatoria', focusDesc: 'Solo palabras difíciles',
    smartDesc: 'Palabras que necesitan repaso', startTest: 'Iniciar prueba',
    whatDoesWordMean: '¿Qué significa esta palabra?', needsMorePractice: 'Necesita más práctica',
    back: 'Volver',
    yourUltimate: 'Tu compañero', studyCompanion: 'de estudio definitivo',
    homeDesc: 'Herramientas inteligentes, organización avanzada y sesiones de estudio — todo en un solo lugar.',
    getStartedFree: 'Empezar gratis', features: 'Características',
    everythingYouNeed: 'Todo lo que necesitas para triunfar',
    readyToTransform: '¿Listo para transformar tus hábitos de estudio?',
    joinStudents: 'Únete a los estudiantes que usan StudyHub.',
    createFreeAccount: 'Crea tu cuenta gratis',
    welcomeBackUser: 'Bienvenido de vuelta,',
    homeWelcomeDesc: 'StudyHub es tu kit de herramientas académicas. Organiza materiales, enfócate con Pomodoro y construye vocabulario — todo sincronizado.',
    goToMaterials: 'Mis materiales',
    installApp: '📱 Instala esta app para acceso sin conexión',
    organizeMaterials: 'Organizar materiales', organizeMaterialsDesc: 'Mantén todo organizado con seguimiento de progreso.',
    pomodoroTimerTitle: 'Temporizador Pomodoro', pomodoroTimerDesc: 'Mantén el enfoque con sesiones personalizables.',
    vocabFlashcards: 'Vocabulario y tarjetas', vocabFlashcardsDesc: 'Construye tu vocabulario con tarjetas de repetición.',
    signInToViewMaterials: 'Inicia sesión para ver materiales', createAccountToSave: 'Crea una cuenta para guardar y sincronizar',
    addMaterial: 'Agregar material', noMaterialsYet: 'Sin materiales aún', addFirstMaterial: '¡Agrega tu primer material!',
    addTask: 'Agregar tarea', total: 'Total', completed: 'Completado', urgent: 'Urgente', overdue: 'Atrasado',
    taskTitle: 'Título de la tarea...', taskDescription: 'Descripción (opcional)',
    deadline: 'Fecha límite', importance: 'Importancia',
    urgentLabel: 'Urgente', mediumLabel: 'Medio', lowLabel: 'Bajo',
    noTasks: 'Sin tareas', addFirstTask: 'Agrega tu primera tarea',
    signInForTodos: 'Inicia sesión para tareas',
    messagesTitle: 'Mensajes y encuestas', noMessages: 'Sin mensajes', markAllRead: 'Marcar todo leído',
    suggestionsTitle: 'Sugerencias', addSuggestion: 'Agregar sugerencia',
    suggestionTitle: 'Título', suggestionDesc: 'Descripción',
    noSuggestions: 'Sin sugerencias', submitSuggestion: 'Enviar',
    study: 'Estudio', shortBreak: 'Descanso corto', longBreak: 'Descanso largo',
    addNewWord: 'Agregar nueva palabra', englishWord: 'Palabra en inglés', enterEnglishWord: 'Ingresa la palabra en inglés...',
    meaningLabel: 'Significado', enterMeaning: 'Ingresa el significado...', notesOptional: 'Notas (Opcional)',
    addNotes: 'Agrega notas adicionales...', adding: 'Agregando...', letters: 'letras',
    english: 'INGLÉS', targetLanguage: 'SIGNIFICADO',
    activePolls: 'Encuestas activas', messagesSection: 'Mensajes',
    noMessagesDesc: 'Los mensajes y encuestas del equipo aparecerán aquí',
    thankYouVote: '¡Gracias por contribuir al desarrollo del sitio! 🎉',
    failedToVote: 'Error al votar', adminMessage: 'Mensaje del administrador',
    helpUsImprove: 'Ayúdanos a mejorar la plataforma',
    beFirstToShare: '¡Sé el primero en compartir tus ideas!',
    shareYourIdea: 'Comparte tu idea', relatedPage: 'Página relacionada',
    briefTitle: 'Título breve para tu sugerencia...',
    describeInDetail: 'Describe tu sugerencia en detalle...',
    submitting: 'Enviando...', submitSuggestionBtn: 'Enviar sugerencia',
    supported: 'Apoyado', supportThisIdea: 'Apoyar esta idea',
    accepted: 'Aceptado', anonymous: 'Anónimo',
    pageGeneral: 'General', pageMaterials: 'Material de estudio', pageVocabulary: 'Vocabulario',
    pagePomodoro: 'Temporizador Pomodoro', pageMessages: 'Mensajes',
    pageSettings: 'Configuración', pageSuggestions: 'Sugerencias',
    focusZone: 'Zona de enfoque',
    subjects: 'materias', subject: 'materia', addCourse: 'Agregar curso',
    noCoursesYet: 'Sin cursos aún', addFirstCourse: 'Agrega tu primer curso para comenzar',
    backToMaterials: 'Volver a materiales', materialNotFound: 'Material no encontrado',
    completedLessons: 'completadas', remainingLessons: 'restantes',
    lessons: 'Lecciones', files: 'Archivos', hasNotes: 'Tiene notas',
    deleteMaterialConfirm: '¿Estás seguro de eliminar este material y todas sus lecciones?',
    deleteLessonConfirm: '¿Eliminar esta lección?',
    toDoList: 'Lista de tareas', stayOrganized: 'Mantente organizado y sigue tu progreso',
    totalTasks: 'Total de tareas', overallProgress: 'Progreso general',
    active: 'Activas', done: 'Hechas',
    allClear: '¡Todo claro!', addFirstTaskDesc: 'Agrega tu primera tarea para empezar',
    createFirstTask: 'Crear primera tarea',
    addNewTask: 'Agregar nueva tarea', title: 'Título', details: 'Detalles',
    whatNeedsToBeDone: '¿Qué hay que hacer?', addMoreContext: 'Agrega más contexto...',
    priority: 'Prioridad', dueDate: 'Fecha de vencimiento', add: 'Agregar',
    overdueWarning: '¡Esta tarea ha pasado su fecha límite!',
    signInToManageTasks: 'Inicia sesión para gestionar tus tareas',
    due: 'Vence',
    signInToAccessSupport: 'Inicia sesión para acceder al soporte técnico',
    createAccountForHelp: 'Crea una cuenta para obtener ayuda de nuestro equipo',
    getHelpFromTeam: 'Obtén ayuda de nuestro equipo',
    newTicket: 'Nuevo ticket', open: 'Abierto', resolved: 'Resuelto',
    noTicketsYet: 'Sin tickets', createTicketHelp: 'Crea un ticket para obtener ayuda',
    createFirstTicket: 'Crear primer ticket',
    newSupportTicket: 'Nuevo ticket de soporte',
    subjectLabel: 'Asunto', briefIssueDesc: 'Breve descripción del problema...',
    messageLabel: 'Mensaje', describeIssueDetail: 'Describe tu problema en detalle...',
    characters: 'caracteres', creating: 'Creando...', submitTicket: 'Enviar ticket',
    noMessagesYetChat: 'Sin mensajes aún — ¡inicia la conversación!',
    typeYourMessage: 'Escribe tu mensaje...',
    signInToPractice: 'Inicia sesión para practicar',
    createAccountForFlashcards: 'Crea una cuenta para usar las tarjetas de práctica',
    allWords: 'Todas',
    supportDesc: '¿Necesitas ayuda? Crea un ticket de soporte y nuestro equipo te asistirá.',
    codeCopied: '¡Código copiado!', yourUniqueCode: 'Tu código único',
    greatJob: '¡Gran trabajo! ¡Estás en llamas! 🔥', taskCompleted: '¡Tarea completada! ¡Sigue así! 💪',
    wellDone: '¡Bien hecho! ¡Un paso más cerca! 🎯', amazing: '¡Increíble! ⭐',
    incredibleProgress: '¡Progreso increíble! 🚀',
    siteGuideTitle: 'Guía del sitio',
    siteGuideSubtitle: 'Descubre todas las funciones',
    infoHome: 'Tu panel personal con estadísticas de estudio, actividad reciente y acceso rápido a todas las funciones.',
    infoMaterials: 'Organiza tus cursos en módulos estructurados. Agrega lecciones con texto enriquecido y exporta como PDF.',
    infoVocabulary: 'Construye y gestiona tu vocabulario. Practica con tarjetas o cuestionarios y rastrea tu dominio.',
    infoPomodoro: 'Mantén el enfoque con la técnica Pomodoro. Personaliza los tiempos de estudio y descanso.',
    infoMessages: 'Lee anuncios y actualizaciones del administrador. Participa en encuestas y mantente informado.',
    infoSuggestions: 'Comparte tus ideas para mejorar la plataforma. Envía solicitudes y vota por las sugerencias.',
    infoTodos: 'Gestiona tareas con prioridades de colores. Establece plazos con cuenta regresiva en vivo.',
    infoSupport: '¿Necesitas ayuda? Crea tickets de soporte, adjunta imágenes y chatea con el equipo.',
    leaderboard: 'Clasificación',
    leaderboardDesc: 'Mejores por tiempo dedicado',
    noLeaderboardData: 'Sin datos aún',
  },
  pt: {
    home: 'Início', studyMaterials: 'Material de estudo', vocabulary: 'Vocabulário',
    createTable: 'Criar tabela', pomodoroTimer: 'Temporizador Pomodoro',
    suggestions: 'Sugestões', messages: 'Mensagens', todoList: 'Lista de tarefas', technicalSupport: 'Suporte técnico',
    settings: 'Configurações', profile: 'Perfil', displayName: 'Nome de exibição',
    save: 'Salvar', avatarColor: 'Cor do avatar', avatarIcon: 'Ícone do avatar',
    changePassword: 'Alterar senha', newPassword: 'Nova senha...',
    confirmPassword: 'Confirmar senha...',
    appearance: 'Aparência', darkMode: 'Modo escuro', darkEnabled: 'Tema escuro ativado',
    lightEnabled: 'Tema claro ativado', sidebarOrder: 'Ordem da barra lateral',
    sidebarDrag: 'Arraste para reordenar os botões de navegação.',
    saveSidebarOrder: 'Salvar ordem', account: 'Conta',
    signOutDesc: 'Sair da sua conta neste dispositivo.', signOut: 'Sair',
    language: 'Idioma', languageDesc: 'Escolha seu idioma preferido',
    addWord: 'Adicionar palavra', practice: 'Praticar', difficult: 'Difícil',
    search: 'Pesquisar...', masteryProgress: 'Progresso de domínio',
    words: 'palavras', mastered: 'dominadas', noDifficultWords: 'Sem palavras difíceis',
    noWordsFound: 'Nenhuma palavra encontrada', noWordsYet: 'Nenhuma palavra ainda',
    greatNoDifficult: 'Ótimo! Nenhuma palavra difícil',
    tryDifferentSearch: 'Tente outro termo', addFirstWord: 'Adicione sua primeira palavra',
    showingDifficult: 'Mostrando palavras difíceis',
    searchingFor: 'Pesquisando', result: 'resultado', results: 'resultados',
    signIn: 'Entrar / Criar conta', myProfile: 'Meu perfil',
    signInBtn: 'Entrar', createAccountBtn: 'Criar conta',
    welcomeBack: 'Bem-vindo de volta', createYourAccount: 'Crie sua conta',
    continueYourJourney: 'Continue sua jornada de aprendizado',
    startYourJourney: 'Comece sua jornada de aprendizado hoje',
    email: 'Email', password: 'Senha', confirmPasswordLabel: 'Confirmar senha',
    howShouldWeCallYou: 'Como devemos chamá-lo?',
    dontHaveAccount: 'Não tem conta?', signUpLink: 'Cadastre-se',
    alreadyHaveAccount: 'Já tem conta?', signInLink: 'Entrar',
    backToHome: 'Voltar ao início', loading: 'Carregando...',
    learnSmarter: 'Aprenda de forma mais inteligente',
    authFeatureDesc: 'Organização inteligente, sessões de estudo focadas e ferramentas poderosas.',
    emailNotAvailable: 'Este email não está disponível',
    displayNameRequired: 'Por favor insira um nome de exibição',
    signupFailed: 'Falha ao criar conta', signinFailed: 'Falha ao entrar',
    accountCreated: 'Conta criada com sucesso!', signedIn: 'Login realizado com sucesso!',
    signInToUse: 'Faça login para usar',
    youAreOffline: 'Offline — dados salvos localmente', hide: 'Ocultar',
    changingPassword: 'Alterando...',
    passwordChanged: 'Senha alterada', passwordsDontMatch: 'As senhas não coincidem',
    passwordTooShort: 'Mínimo 6 caracteres', displayNameUpdated: 'Nome atualizado',
    sidebarOrderSaved: 'Ordem salva',
    testComplete: 'Teste completo!', wordsReviewed: 'palavras revisadas',
    easy: 'Fácil', hard: 'Difícil', failed: 'Reprovado', wordsToReview: 'Palavras para revisar',
    testAgain: 'Testar novamente', backToVocabulary: 'Voltar ao vocabulário',
    numberOfWords: 'Número de palavras', testType: 'Tipo de teste', testFormat: 'Formato de teste',
    flashcards: 'Cartões', multipleChoice: 'Múltipla escolha',
    flipToReveal: 'Vire para revelar', pickCorrect: 'Escolha a resposta correta',
    random: 'Aleatório', focus: 'Focado', smartReview: 'Revisão inteligente',
    randomDesc: 'Seleção aleatória', focusDesc: 'Apenas palavras difíceis',
    smartDesc: 'Palavras que precisam de revisão', startTest: 'Iniciar teste',
    whatDoesWordMean: 'O que esta palavra significa?', needsMorePractice: 'Precisa de mais prática',
    back: 'Voltar',
    yourUltimate: 'Seu companheiro', studyCompanion: 'de estudo definitivo',
    homeDesc: 'Ferramentas inteligentes, organização avançada e sessões de estudo — tudo em um só lugar.',
    getStartedFree: 'Comece grátis', features: 'Recursos',
    everythingYouNeed: 'Tudo que você precisa para ter sucesso',
    readyToTransform: 'Pronto para transformar seus hábitos de estudo?',
    joinStudents: 'Junte-se aos alunos que usam o StudyHub.',
    createFreeAccount: 'Crie sua conta grátis',
    welcomeBackUser: 'Bem-vindo de volta,',
    homeWelcomeDesc: 'StudyHub é seu kit completo. Organize materiais, foque com Pomodoro e construa vocabulário — tudo sincronizado.',
    goToMaterials: 'Meus materiais',
    installApp: '📱 Instale este app para acesso offline',
    organizeMaterials: 'Organizar materiais', organizeMaterialsDesc: 'Mantenha tudo organizado com acompanhamento de progresso.',
    pomodoroTimerTitle: 'Temporizador Pomodoro', pomodoroTimerDesc: 'Mantenha o foco com sessões personalizáveis.',
    vocabFlashcards: 'Vocabulário e cartões', vocabFlashcardsDesc: 'Construa vocabulário com repetição espaçada.',
    signInToViewMaterials: 'Faça login para ver materiais', createAccountToSave: 'Crie uma conta para salvar e sincronizar',
    addMaterial: 'Adicionar material', noMaterialsYet: 'Nenhum material ainda', addFirstMaterial: 'Adicione seu primeiro material!',
    addTask: 'Adicionar tarefa', total: 'Total', completed: 'Concluído', urgent: 'Urgente', overdue: 'Atrasado',
    taskTitle: 'Título da tarefa...', taskDescription: 'Descrição (opcional)',
    deadline: 'Prazo', importance: 'Importância',
    urgentLabel: 'Urgente', mediumLabel: 'Médio', lowLabel: 'Baixo',
    noTasks: 'Nenhuma tarefa', addFirstTask: 'Adicione sua primeira tarefa',
    signInForTodos: 'Faça login para tarefas',
    messagesTitle: 'Mensagens e enquetes', noMessages: 'Nenhuma mensagem', markAllRead: 'Marcar tudo lido',
    suggestionsTitle: 'Sugestões', addSuggestion: 'Adicionar sugestão',
    suggestionTitle: 'Título', suggestionDesc: 'Descrição',
    noSuggestions: 'Nenhuma sugestão', submitSuggestion: 'Enviar',
    study: 'Estudo', shortBreak: 'Pausa curta', longBreak: 'Pausa longa',
    addNewWord: 'Adicionar nova palavra', englishWord: 'Palavra em inglês', enterEnglishWord: 'Digite a palavra em inglês...',
    meaningLabel: 'Significado', enterMeaning: 'Digite o significado...', notesOptional: 'Notas (Opcional)',
    addNotes: 'Adicione notas adicionais...', adding: 'Adicionando...', letters: 'letras',
    english: 'INGLÊS', targetLanguage: 'SIGNIFICADO',
    activePolls: 'Enquetes ativas', messagesSection: 'Mensagens',
    noMessagesDesc: 'Mensagens e enquetes da equipe aparecerão aqui',
    thankYouVote: 'Obrigado por contribuir para o desenvolvimento do site! 🎉',
    failedToVote: 'Falha ao votar', adminMessage: 'Mensagem do administrador',
    helpUsImprove: 'Ajude-nos a melhorar a plataforma',
    beFirstToShare: 'Seja o primeiro a compartilhar suas ideias!',
    shareYourIdea: 'Compartilhe sua ideia', relatedPage: 'Página relacionada',
    briefTitle: 'Título breve para sua sugestão...',
    describeInDetail: 'Descreva sua sugestão em detalhes...',
    submitting: 'Enviando...', submitSuggestionBtn: 'Enviar sugestão',
    supported: 'Apoiado', supportThisIdea: 'Apoiar esta ideia',
    accepted: 'Aceito', anonymous: 'Anônimo',
    pageGeneral: 'Geral', pageMaterials: 'Material de estudo', pageVocabulary: 'Vocabulário',
    pagePomodoro: 'Temporizador Pomodoro', pageMessages: 'Mensagens',
    pageSettings: 'Configurações', pageSuggestions: 'Sugestões',
    focusZone: 'Zona de foco',
    subjects: 'disciplinas', subject: 'disciplina', addCourse: 'Adicionar curso',
    noCoursesYet: 'Sem cursos ainda', addFirstCourse: 'Adicione seu primeiro curso para começar',
    backToMaterials: 'Voltar aos materiais', materialNotFound: 'Material não encontrado',
    completedLessons: 'concluídas', remainingLessons: 'restantes',
    lessons: 'Aulas', files: 'Arquivos', hasNotes: 'Tem notas',
    deleteMaterialConfirm: 'Tem certeza que deseja excluir este material e todas as aulas?',
    deleteLessonConfirm: 'Excluir esta aula?',
    toDoList: 'Lista de tarefas', stayOrganized: 'Mantenha-se organizado e acompanhe seu progresso',
    totalTasks: 'Total de tarefas', overallProgress: 'Progresso geral',
    active: 'Ativas', done: 'Feitas',
    allClear: 'Tudo limpo!', addFirstTaskDesc: 'Adicione sua primeira tarefa para começar',
    createFirstTask: 'Criar primeira tarefa',
    addNewTask: 'Adicionar nova tarefa', title: 'Título', details: 'Detalhes',
    whatNeedsToBeDone: 'O que precisa ser feito?', addMoreContext: 'Adicione mais contexto...',
    priority: 'Prioridade', dueDate: 'Data de vencimento', add: 'Adicionar',
    overdueWarning: 'Esta tarefa ultrapassou o prazo!',
    signInToManageTasks: 'Faça login para gerenciar suas tarefas',
    due: 'Vence',
    signInToAccessSupport: 'Faça login para acessar o suporte técnico',
    createAccountForHelp: 'Crie uma conta para obter ajuda da nossa equipe',
    getHelpFromTeam: 'Obtenha ajuda da nossa equipe',
    newTicket: 'Novo ticket', open: 'Aberto', resolved: 'Resolvido',
    noTicketsYet: 'Sem tickets', createTicketHelp: 'Crie um ticket para obter ajuda',
    createFirstTicket: 'Criar primeiro ticket',
    newSupportTicket: 'Novo ticket de suporte',
    subjectLabel: 'Assunto', briefIssueDesc: 'Breve descrição do seu problema...',
    messageLabel: 'Mensagem', describeIssueDetail: 'Descreva seu problema em detalhes...',
    characters: 'caracteres', creating: 'Criando...', submitTicket: 'Enviar ticket',
    noMessagesYetChat: 'Sem mensagens ainda — inicie a conversa!',
    typeYourMessage: 'Digite sua mensagem...',
    signInToPractice: 'Faça login para praticar',
    createAccountForFlashcards: 'Crie uma conta para usar os cartões de prática',
    allWords: 'Todas',
    supportDesc: 'Precisa de ajuda? Crie um ticket de suporte e nossa equipe irá ajudá-lo.',
    codeCopied: 'Código copiado!', yourUniqueCode: 'Seu código único',
    greatJob: 'Ótimo trabalho! Você está pegando fogo! 🔥', taskCompleted: 'Tarefa concluída! Continue! 💪',
    wellDone: 'Muito bem! Mais um passo! 🎯', amazing: 'Incrível! ⭐',
    incredibleProgress: 'Progresso incrível! 🚀',
    siteGuideTitle: 'Guia do site',
    siteGuideSubtitle: 'Descubra todos os recursos',
    infoHome: 'Seu painel pessoal com estatísticas de estudo, atividade recente e acesso rápido a todos os recursos.',
    infoMaterials: 'Organize seus cursos em módulos estruturados. Adicione aulas com texto rico e exporte como PDF.',
    infoVocabulary: 'Construa e gerencie seu vocabulário. Pratique com cartões ou quiz e acompanhe seu domínio.',
    infoPomodoro: 'Mantenha o foco com a técnica Pomodoro. Personalize os tempos de estudo e descanso.',
    infoMessages: 'Leia anúncios e atualizações do administrador. Participe de enquetes e fique informado.',
    infoSuggestions: 'Compartilhe suas ideias para melhorar a plataforma. Envie solicitações e vote nas sugestões.',
    infoTodos: 'Gerencie tarefas com prioridades coloridas. Defina prazos com contagem regressiva ao vivo.',
    infoSupport: 'Precisa de ajuda? Crie tickets de suporte, anexe imagens e converse com a equipe.',
    leaderboard: 'Classificação',
    leaderboardDesc: 'Melhores por tempo dedicado',
    noLeaderboardData: 'Sem dados ainda',
  },
};

const RTL_LANGUAGES: Language[] = ['ar'];

const LANGUAGE_INFO: { code: Language; name: string; nativeName: string; flag: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
  dir: 'ltr' | 'rtl';
  LANGUAGE_INFO: typeof LANGUAGE_INFO;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
  isRTL: false,
  dir: 'ltr',
  LANGUAGE_INFO,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { settings, updateSettings } = useUserSettings();
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    if (settings?.language) {
      setLanguageState(settings.language as Language);
    }
  }, [settings?.language]);

  useEffect(() => {
    const isRTL = RTL_LANGUAGES.includes(language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    updateSettings({ language: lang } as any);
  }, [updateSettings]);

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  }, [language]);

  const isRTL = RTL_LANGUAGES.includes(language);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL, dir: isRTL ? 'rtl' : 'ltr', LANGUAGE_INFO }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
