import { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react';
import { useUserSettings } from '@/hooks/useUserSettings';

export type Language = 'en' | 'ar' | 'fr' | 'zh' | 'ja' | 'hi' | 'es' | 'pt';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  en: {
    // Navigation
    home: 'Home', studyMaterials: 'Study Materials', vocabulary: 'Vocabulary',
    aiStudyChat: 'AI Study Chat', createTable: 'Create Table', pomodoroTimer: 'Pomodoro Timer',
    suggestions: 'Suggestions', messages: 'Messages', todoList: 'To-Do List', technicalSupport: 'Technical Support',
    // Settings
    settings: 'Settings', profile: 'Profile', displayName: 'Display Name',
    save: 'Save', avatarColor: 'Avatar Color', avatarIcon: 'Avatar Icon',
    changePassword: 'Change Password', newPassword: 'New password...',
    confirmPassword: 'Confirm new password...', aiPreferences: 'AI Preferences',
    appearance: 'Appearance', darkMode: 'Dark Mode', darkEnabled: 'Dark theme enabled',
    lightEnabled: 'Light theme enabled', sidebarOrder: 'Sidebar Order',
    sidebarDrag: 'Drag and drop to reorder the sidebar navigation buttons.',
    saveSidebarOrder: 'Save Sidebar Order', account: 'Account',
    signOutDesc: 'Sign out of your account on this device.', signOut: 'Sign Out',
    language: 'Language', languageDesc: 'Choose your preferred language',
    // Vocabulary
    addWord: 'Add Word', practice: 'Practice', difficult: 'Difficult',
    search: 'Search in English or Arabic...', masteryProgress: 'Mastery Progress',
    words: 'words', mastered: 'mastered', noDifficultWords: 'No difficult words',
    noWordsFound: 'No words found', noWordsYet: 'No words yet',
    greatNoDifficult: 'Great! No words are marked as difficult',
    tryDifferentSearch: 'Try a different search term',
    addFirstWord: 'Add your first vocabulary word to get started',
    showingDifficult: 'Showing difficult words that need more review',
    // AI Chat
    askAnything: 'Ask anything about your studies...', howCanIHelp: 'How can I help you today?',
    aiDesc: 'Ask me anything about your studies. I can help with explanations, summaries, practice questions, image analysis, and more.',
    signInToUse: 'Sign in to use', analyzing: 'Analyzing...', thinking: 'Thinking...',
    generating: 'Generating response...', processing: 'Processing...',
    uploadImage: 'Upload Image', takePhoto: 'Take Photo',
    // Auth
    signIn: 'Sign In / Create Account', myProfile: 'My Profile',
    signInBtn: 'Sign In', createAccountBtn: 'Create Account',
    welcomeBack: 'Welcome back', createYourAccount: 'Create your account',
    continueYourJourney: 'Continue your learning journey',
    startYourJourney: 'Start your learning journey today',
    email: 'Email', password: 'Password', confirmPasswordLabel: 'Confirm Password',
    howShouldWeCallYou: 'How should we call you?',
    dontHaveAccount: "Don't have an account?", signUpLink: 'Sign up',
    alreadyHaveAccount: 'Already have an account?', signInLink: 'Sign in',
    backToHome: 'Back to home', loading: 'Loading...',
    learnSmarter: 'Learn Smarter, Study Better',
    authFeatureDesc: 'AI-powered tools, smart organization, and focused study sessions — everything you need to excel.',
    emailNotAvailable: 'This email address is not available for registration',
    displayNameRequired: 'Please enter a display name',
    signupFailed: 'Failed to create account', signinFailed: 'Failed to sign in',
    accountCreated: 'Account created successfully!', signedIn: 'Signed in successfully!',
    // Offline
    youAreOffline: 'You are offline — data is saved locally', hide: 'Hide',
    // Settings misc
    customizeAi: 'Customize how the AI responds to you. This prompt will be included in all AI conversations.',
    aiPlaceholder: 'e.g., Explain things simply, use examples, be encouraging...',
    saveAiPrefs: 'Save AI Preferences', changingPassword: 'Changing...',
    passwordChanged: 'Password changed successfully', passwordsDontMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    displayNameUpdated: 'Display name updated', aiPrefsUpdated: 'AI preferences updated',
    sidebarOrderSaved: 'Sidebar order saved',
    // Flashcards
    testComplete: 'Test Complete!', wordsReviewed: 'words reviewed',
    easy: 'Easy', hard: 'Hard', failed: 'Failed', wordsToReview: 'Words to Review',
    testAgain: 'Test Again', backToVocabulary: 'Back to Vocabulary',
    numberOfWords: 'Number of Words', testType: 'Test Type', testFormat: 'Test Format',
    flashcards: 'Flashcards', multipleChoice: 'Multiple Choice',
    flipToReveal: 'Flip to reveal meaning', pickCorrect: 'Pick the correct answer',
    random: 'Random', focus: 'Focus', smartReview: 'Smart Review',
    randomDesc: 'Random selection of words', focusDesc: 'Only words rated poor or difficult',
    smartDesc: 'Words needing review based on algorithm', startTest: 'Start Test',
    whatDoesWordMean: 'What does this word mean?', needsMorePractice: 'Needs more practice',
    back: 'Back',
    // Home page
    yourUltimate: 'Your Ultimate', studyCompanion: 'Study Companion',
    homeDesc: 'AI-powered tools, smart organization, and focused study sessions — everything you need to ace your studies, all in one place.',
    getStartedFree: 'Get Started Free', features: 'Features',
    everythingYouNeed: 'Everything You Need to Succeed',
    readyToTransform: 'Ready to Transform Your Study Habits?',
    joinStudents: 'Join students who are already using StudyHub to organize, focus, and succeed in their academic journey.',
    createFreeAccount: 'Create Your Free Account',
    welcomeBackUser: 'Welcome back,',
    homeWelcomeDesc: 'StudyHub is your all-in-one academic toolkit. Organize your course materials, study with AI-powered assistance, stay focused with Pomodoro sessions, and build your vocabulary — all synced across your devices.',
    goToMaterials: 'Go to My Materials',
    installApp: '📱 Install this app on your device for offline access',
    // Feature titles
    aiStudyAssistant: 'AI Study Assistant',
    aiStudyAssistantDesc: 'Chat with an intelligent AI tutor that can summarize, explain, and help you understand any topic with precision.',
    organizeMaterials: 'Organize Materials',
    organizeMaterialsDesc: 'Keep all your courses, lessons, and files perfectly organized in one place with progress tracking.',
    pomodoroTimerTitle: 'Pomodoro Timer',
    pomodoroTimerDesc: 'Stay focused with customizable study sessions, break intervals, and ambient nature sounds.',
    vocabFlashcards: 'Vocabulary & Flashcards',
    vocabFlashcardsDesc: 'Build your vocabulary with spaced repetition flashcards and track your memorization progress.',
    // Materials page
    signInToViewMaterials: 'Sign in to view materials',
    createAccountToSave: 'Create an account to save and sync your study materials',
    addMaterial: 'Add Material', noMaterialsYet: 'No materials yet',
    addFirstMaterial: 'Add your first study material to get started!',
    // Todo page
    addTask: 'Add Task', total: 'Total', completed: 'Completed', urgent: 'Urgent', overdue: 'Overdue',
    taskTitle: 'Task title...', taskDescription: 'Description (optional)',
    deadline: 'Deadline', importance: 'Importance',
    urgentLabel: 'Urgent', mediumLabel: 'Medium', lowLabel: 'Low',
    noTasks: 'No tasks yet', addFirstTask: 'Add your first task to get started',
    signInForTodos: 'Sign in to use To-Do List',
    // Messages page
    messagesTitle: 'Messages & Polls', noMessages: 'No messages yet',
    markAllRead: 'Mark all read',
    // Suggestions page
    suggestionsTitle: 'Suggestions', addSuggestion: 'Add Suggestion',
    suggestionTitle: 'Title', suggestionDesc: 'Description',
    noSuggestions: 'No suggestions yet', submitSuggestion: 'Submit',
    // Table creator
    tableCreatorTitle: 'Create Table',
    tableCreatorDesc: 'Design beautiful tables with custom formatting and download as images.',
    // Pomodoro
    study: 'Study', shortBreak: 'Short Break', longBreak: 'Long Break',
  },
  ar: {
    home: 'الرئيسية', studyMaterials: 'المواد الدراسية', vocabulary: 'المفردات',
    aiStudyChat: 'محادثة الذكاء الاصطناعي', createTable: 'إنشاء جدول', pomodoroTimer: 'مؤقت بومودورو',
    suggestions: 'الاقتراحات', messages: 'الرسائل', todoList: 'قائمة المهام', technicalSupport: 'الدعم الفني',
    settings: 'الإعدادات', profile: 'الملف الشخصي', displayName: 'اسم العرض',
    save: 'حفظ', avatarColor: 'لون الصورة الرمزية', avatarIcon: 'أيقونة الصورة الرمزية',
    changePassword: 'تغيير كلمة المرور', newPassword: 'كلمة المرور الجديدة...',
    confirmPassword: 'تأكيد كلمة المرور...', aiPreferences: 'تفضيلات الذكاء الاصطناعي',
    appearance: 'المظهر', darkMode: 'الوضع الداكن', darkEnabled: 'الوضع الداكن مفعّل',
    lightEnabled: 'الوضع الفاتح مفعّل', sidebarOrder: 'ترتيب الشريط الجانبي',
    sidebarDrag: 'اسحب وأفلت لإعادة ترتيب أزرار التنقل.',
    saveSidebarOrder: 'حفظ ترتيب الشريط الجانبي', account: 'الحساب',
    signOutDesc: 'تسجيل الخروج من حسابك على هذا الجهاز.', signOut: 'تسجيل الخروج',
    language: 'اللغة', languageDesc: 'اختر لغتك المفضلة',
    addWord: 'إضافة كلمة', practice: 'تدريب', difficult: 'صعبة',
    search: 'ابحث بالإنجليزية أو العربية...', masteryProgress: 'تقدم الإتقان',
    words: 'كلمات', mastered: 'تم إتقانها', noDifficultWords: 'لا توجد كلمات صعبة',
    noWordsFound: 'لم يتم العثور على كلمات', noWordsYet: 'لا توجد كلمات بعد',
    greatNoDifficult: 'رائع! لا توجد كلمات مصنفة كصعبة',
    tryDifferentSearch: 'جرّب مصطلح بحث مختلف',
    addFirstWord: 'أضف أول كلمة مفردات للبدء',
    showingDifficult: 'عرض الكلمات الصعبة التي تحتاج مراجعة',
    askAnything: 'اسأل أي شيء عن دراستك...', howCanIHelp: 'كيف يمكنني مساعدتك اليوم؟',
    aiDesc: 'اسألني أي شيء عن دراستك. يمكنني المساعدة في الشروحات والملخصات وأسئلة التدريب وتحليل الصور والمزيد.',
    signInToUse: 'سجّل الدخول للاستخدام', analyzing: 'جارٍ التحليل...', thinking: 'جارٍ التفكير...',
    generating: 'جارٍ إنشاء الرد...', processing: 'جارٍ المعالجة...',
    uploadImage: 'رفع صورة', takePhoto: 'التقاط صورة',
    signIn: 'تسجيل الدخول / إنشاء حساب', myProfile: 'ملفي الشخصي',
    signInBtn: 'تسجيل الدخول', createAccountBtn: 'إنشاء حساب',
    welcomeBack: 'مرحباً بعودتك', createYourAccount: 'إنشاء حسابك',
    continueYourJourney: 'تابع رحلة تعلمك',
    startYourJourney: 'ابدأ رحلة تعلمك اليوم',
    email: 'البريد الإلكتروني', password: 'كلمة المرور', confirmPasswordLabel: 'تأكيد كلمة المرور',
    howShouldWeCallYou: 'ماذا نناديك؟',
    dontHaveAccount: 'ليس لديك حساب؟', signUpLink: 'إنشاء حساب',
    alreadyHaveAccount: 'لديك حساب بالفعل؟', signInLink: 'تسجيل الدخول',
    backToHome: 'العودة للرئيسية', loading: 'جارٍ التحميل...',
    learnSmarter: 'تعلّم بذكاء، ادرس بكفاءة',
    authFeatureDesc: 'أدوات مدعومة بالذكاء الاصطناعي، تنظيم ذكي، وجلسات دراسة مركّزة — كل ما تحتاجه للتفوق.',
    emailNotAvailable: 'هذا البريد الإلكتروني غير متاح للتسجيل',
    displayNameRequired: 'يرجى إدخال اسم العرض',
    signupFailed: 'فشل في إنشاء الحساب', signinFailed: 'فشل في تسجيل الدخول',
    accountCreated: 'تم إنشاء الحساب بنجاح!', signedIn: 'تم تسجيل الدخول بنجاح!',
    youAreOffline: 'أنت غير متصل — البيانات محفوظة محلياً', hide: 'إخفاء',
    customizeAi: 'خصّص طريقة استجابة الذكاء الاصطناعي لك.',
    aiPlaceholder: 'مثال: اشرح الأشياء ببساطة، استخدم أمثلة...',
    saveAiPrefs: 'حفظ تفضيلات الذكاء الاصطناعي', changingPassword: 'جارٍ التغيير...',
    passwordChanged: 'تم تغيير كلمة المرور بنجاح', passwordsDontMatch: 'كلمات المرور غير متطابقة',
    passwordTooShort: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    displayNameUpdated: 'تم تحديث اسم العرض', aiPrefsUpdated: 'تم تحديث تفضيلات الذكاء الاصطناعي',
    sidebarOrderSaved: 'تم حفظ ترتيب الشريط الجانبي',
    testComplete: 'اكتمل الاختبار!', wordsReviewed: 'كلمات تمت مراجعتها',
    easy: 'سهل', hard: 'صعب', failed: 'فشل', wordsToReview: 'كلمات للمراجعة',
    testAgain: 'اختبار مرة أخرى', backToVocabulary: 'العودة للمفردات',
    numberOfWords: 'عدد الكلمات', testType: 'نوع الاختبار', testFormat: 'تنسيق الاختبار',
    flashcards: 'بطاقات تعليمية', multipleChoice: 'اختيار من متعدد',
    flipToReveal: 'اقلب لكشف المعنى', pickCorrect: 'اختر الإجابة الصحيحة',
    random: 'عشوائي', focus: 'تركيز', smartReview: 'مراجعة ذكية',
    randomDesc: 'اختيار عشوائي للكلمات', focusDesc: 'فقط الكلمات المصنفة ضعيفة أو صعبة',
    smartDesc: 'كلمات تحتاج مراجعة حسب الخوارزمية', startTest: 'ابدأ الاختبار',
    whatDoesWordMean: 'ماذا تعني هذه الكلمة؟', needsMorePractice: 'تحتاج مزيداً من التدريب',
    back: 'رجوع',
    yourUltimate: 'رفيقك الأمثل', studyCompanion: 'في الدراسة',
    homeDesc: 'أدوات مدعومة بالذكاء الاصطناعي، تنظيم ذكي، وجلسات دراسة مركّزة — كل ما تحتاجه للتفوق في دراستك.',
    getStartedFree: 'ابدأ مجاناً', features: 'المميزات',
    everythingYouNeed: 'كل ما تحتاجه للنجاح',
    readyToTransform: 'مستعد لتحويل عاداتك الدراسية؟',
    joinStudents: 'انضم للطلاب الذين يستخدمون StudyHub للتنظيم والتركيز والنجاح.',
    createFreeAccount: 'أنشئ حسابك المجاني',
    welcomeBackUser: 'مرحباً بعودتك،',
    homeWelcomeDesc: 'StudyHub هو مجموعة أدواتك الأكاديمية الشاملة. نظّم موادك الدراسية، ادرس بمساعدة الذكاء الاصطناعي، حافظ على تركيزك مع جلسات بومودورو، وابنِ مفرداتك — كلها متزامنة عبر أجهزتك.',
    goToMaterials: 'اذهب لموادي',
    installApp: '📱 ثبّت هذا التطبيق على جهازك للوصول بدون إنترنت',
    aiStudyAssistant: 'مساعد دراسة ذكي',
    aiStudyAssistantDesc: 'تحدث مع معلم ذكي يمكنه التلخيص والشرح ومساعدتك على فهم أي موضوع.',
    organizeMaterials: 'تنظيم المواد',
    organizeMaterialsDesc: 'احتفظ بكل دروسك وملفاتك منظمة في مكان واحد مع تتبع التقدم.',
    pomodoroTimerTitle: 'مؤقت بومودورو',
    pomodoroTimerDesc: 'حافظ على تركيزك مع جلسات دراسة قابلة للتخصيص وفترات راحة وأصوات طبيعية.',
    vocabFlashcards: 'المفردات والبطاقات التعليمية',
    vocabFlashcardsDesc: 'ابنِ مفرداتك ببطاقات التكرار المتباعد وتتبع تقدمك في الحفظ.',
    signInToViewMaterials: 'سجّل الدخول لعرض المواد',
    createAccountToSave: 'أنشئ حساباً لحفظ ومزامنة موادك الدراسية',
    addMaterial: 'إضافة مادة', noMaterialsYet: 'لا توجد مواد بعد',
    addFirstMaterial: 'أضف أول مادة دراسية للبدء!',
    addTask: 'إضافة مهمة', total: 'الإجمالي', completed: 'مكتمل', urgent: 'عاجل', overdue: 'متأخر',
    taskTitle: 'عنوان المهمة...', taskDescription: 'الوصف (اختياري)',
    deadline: 'الموعد النهائي', importance: 'الأهمية',
    urgentLabel: 'عاجل', mediumLabel: 'متوسط', lowLabel: 'منخفض',
    noTasks: 'لا توجد مهام بعد', addFirstTask: 'أضف أول مهمة للبدء',
    signInForTodos: 'سجّل الدخول لاستخدام قائمة المهام',
    messagesTitle: 'الرسائل والاستطلاعات', noMessages: 'لا توجد رسائل بعد',
    markAllRead: 'تحديد الكل كمقروء',
    suggestionsTitle: 'الاقتراحات', addSuggestion: 'إضافة اقتراح',
    suggestionTitle: 'العنوان', suggestionDesc: 'الوصف',
    noSuggestions: 'لا توجد اقتراحات بعد', submitSuggestion: 'إرسال',
    tableCreatorTitle: 'إنشاء جدول',
    tableCreatorDesc: 'صمم جداول جميلة بتنسيق مخصص وحمّلها كصور.',
    study: 'دراسة', shortBreak: 'استراحة قصيرة', longBreak: 'استراحة طويلة',
  },
  fr: {
    home: 'Accueil', studyMaterials: 'Matériel d\'étude', vocabulary: 'Vocabulaire',
    aiStudyChat: 'Chat IA', createTable: 'Créer un tableau', pomodoroTimer: 'Minuteur Pomodoro',
    suggestions: 'Suggestions', messages: 'Messages', todoList: 'Liste de tâches', technicalSupport: 'Support technique',
    settings: 'Paramètres', profile: 'Profil', displayName: 'Nom d\'affichage',
    save: 'Enregistrer', avatarColor: 'Couleur de l\'avatar', avatarIcon: 'Icône de l\'avatar',
    changePassword: 'Changer le mot de passe', newPassword: 'Nouveau mot de passe...',
    confirmPassword: 'Confirmer le mot de passe...', aiPreferences: 'Préférences IA',
    appearance: 'Apparence', darkMode: 'Mode sombre', darkEnabled: 'Thème sombre activé',
    lightEnabled: 'Thème clair activé', sidebarOrder: 'Ordre de la barre latérale',
    sidebarDrag: 'Glissez-déposez pour réorganiser les boutons de navigation.',
    saveSidebarOrder: 'Enregistrer l\'ordre', account: 'Compte',
    signOutDesc: 'Déconnectez-vous de votre compte.', signOut: 'Déconnexion',
    language: 'Langue', languageDesc: 'Choisissez votre langue préférée',
    addWord: 'Ajouter un mot', practice: 'Pratiquer', difficult: 'Difficile',
    search: 'Rechercher...', masteryProgress: 'Progression de maîtrise',
    words: 'mots', mastered: 'maîtrisés', noDifficultWords: 'Pas de mots difficiles',
    noWordsFound: 'Aucun mot trouvé', noWordsYet: 'Pas encore de mots',
    greatNoDifficult: 'Super ! Aucun mot n\'est marqué comme difficile',
    tryDifferentSearch: 'Essayez un autre terme', addFirstWord: 'Ajoutez votre premier mot',
    showingDifficult: 'Affichage des mots difficiles',
    askAnything: 'Posez une question...', howCanIHelp: 'Comment puis-je vous aider ?',
    aiDesc: 'Posez-moi n\'importe quelle question sur vos études.',
    signInToUse: 'Connectez-vous', analyzing: 'Analyse...', thinking: 'Réflexion...',
    generating: 'Génération...', processing: 'Traitement...',
    uploadImage: 'Télécharger une image', takePhoto: 'Prendre une photo',
    signIn: 'Connexion / Créer un compte', myProfile: 'Mon profil',
    signInBtn: 'Se connecter', createAccountBtn: 'Créer un compte',
    welcomeBack: 'Bienvenue', createYourAccount: 'Créez votre compte',
    continueYourJourney: 'Continuez votre parcours d\'apprentissage',
    startYourJourney: 'Commencez votre parcours d\'apprentissage',
    email: 'Email', password: 'Mot de passe', confirmPasswordLabel: 'Confirmer le mot de passe',
    howShouldWeCallYou: 'Comment devons-nous vous appeler ?',
    dontHaveAccount: 'Pas de compte ?', signUpLink: 'Créer un compte',
    alreadyHaveAccount: 'Déjà un compte ?', signInLink: 'Se connecter',
    backToHome: 'Retour à l\'accueil', loading: 'Chargement...',
    learnSmarter: 'Apprenez plus intelligemment',
    authFeatureDesc: 'Outils IA, organisation intelligente et sessions d\'étude concentrées.',
    emailNotAvailable: 'Cette adresse email n\'est pas disponible',
    displayNameRequired: 'Veuillez entrer un nom d\'affichage',
    signupFailed: 'Échec de la création du compte', signinFailed: 'Échec de la connexion',
    accountCreated: 'Compte créé avec succès !', signedIn: 'Connecté avec succès !',
    youAreOffline: 'Hors ligne — données sauvegardées localement', hide: 'Masquer',
    customizeAi: 'Personnalisez les réponses de l\'IA.',
    aiPlaceholder: 'Ex: Expliquez simplement, utilisez des exemples...',
    saveAiPrefs: 'Enregistrer les préférences IA', changingPassword: 'Changement...',
    passwordChanged: 'Mot de passe changé', passwordsDontMatch: 'Les mots de passe ne correspondent pas',
    passwordTooShort: 'Au moins 6 caractères', displayNameUpdated: 'Nom mis à jour',
    aiPrefsUpdated: 'Préférences IA mises à jour', sidebarOrderSaved: 'Ordre sauvegardé',
    testComplete: 'Test terminé !', wordsReviewed: 'mots révisés',
    easy: 'Facile', hard: 'Difficile', failed: 'Échoué', wordsToReview: 'Mots à revoir',
    testAgain: 'Refaire le test', backToVocabulary: 'Retour au vocabulaire',
    numberOfWords: 'Nombre de mots', testType: 'Type de test', testFormat: 'Format de test',
    flashcards: 'Cartes mémoire', multipleChoice: 'Choix multiple',
    flipToReveal: 'Retournez pour révéler', pickCorrect: 'Choisissez la bonne réponse',
    random: 'Aléatoire', focus: 'Concentré', smartReview: 'Révision intelligente',
    randomDesc: 'Sélection aléatoire', focusDesc: 'Mots difficiles uniquement',
    smartDesc: 'Mots nécessitant une révision', startTest: 'Commencer le test',
    whatDoesWordMean: 'Que signifie ce mot ?', needsMorePractice: 'Besoin de plus de pratique',
    back: 'Retour',
    yourUltimate: 'Votre compagnon', studyCompanion: 'd\'étude ultime',
    homeDesc: 'Outils IA, organisation intelligente et sessions d\'étude — tout ce dont vous avez besoin pour réussir.',
    getStartedFree: 'Commencer gratuitement', features: 'Fonctionnalités',
    everythingYouNeed: 'Tout ce dont vous avez besoin',
    readyToTransform: 'Prêt à transformer vos habitudes d\'étude ?',
    joinStudents: 'Rejoignez les étudiants qui utilisent StudyHub.',
    createFreeAccount: 'Créer un compte gratuit',
    welcomeBackUser: 'Bienvenue,',
    homeWelcomeDesc: 'StudyHub est votre boîte à outils académique complète.',
    goToMaterials: 'Mes matériaux',
    installApp: '📱 Installez cette application pour un accès hors ligne',
    aiStudyAssistant: 'Assistant IA', aiStudyAssistantDesc: 'Discutez avec un tuteur IA intelligent.',
    organizeMaterials: 'Organiser les matériaux', organizeMaterialsDesc: 'Gardez tout organisé.',
    pomodoroTimerTitle: 'Minuteur Pomodoro', pomodoroTimerDesc: 'Restez concentré.',
    vocabFlashcards: 'Vocabulaire et cartes', vocabFlashcardsDesc: 'Construisez votre vocabulaire.',
    signInToViewMaterials: 'Connectez-vous pour voir les matériaux',
    createAccountToSave: 'Créez un compte pour sauvegarder',
    addMaterial: 'Ajouter un matériau', noMaterialsYet: 'Pas encore de matériaux',
    addFirstMaterial: 'Ajoutez votre premier matériau !',
    addTask: 'Ajouter une tâche', total: 'Total', completed: 'Terminé', urgent: 'Urgent', overdue: 'En retard',
    taskTitle: 'Titre de la tâche...', taskDescription: 'Description (optionnel)',
    deadline: 'Date limite', importance: 'Importance',
    urgentLabel: 'Urgent', mediumLabel: 'Moyen', lowLabel: 'Faible',
    noTasks: 'Aucune tâche', addFirstTask: 'Ajoutez votre première tâche',
    signInForTodos: 'Connectez-vous pour les tâches',
    messagesTitle: 'Messages et sondages', noMessages: 'Aucun message',
    markAllRead: 'Tout marquer comme lu',
    suggestionsTitle: 'Suggestions', addSuggestion: 'Ajouter une suggestion',
    suggestionTitle: 'Titre', suggestionDesc: 'Description',
    noSuggestions: 'Aucune suggestion', submitSuggestion: 'Envoyer',
    tableCreatorTitle: 'Créer un tableau',
    tableCreatorDesc: 'Créez de beaux tableaux avec un formatage personnalisé.',
    study: 'Étude', shortBreak: 'Pause courte', longBreak: 'Pause longue',
  },
  zh: {
    home: '首页', studyMaterials: '学习资料', vocabulary: '词汇',
    aiStudyChat: 'AI学习聊天', createTable: '创建表格', pomodoroTimer: '番茄钟',
    suggestions: '建议', messages: '消息', todoList: '待办事项', technicalSupport: '技术支持',
    settings: '设置', profile: '个人资料', displayName: '显示名称',
    save: '保存', avatarColor: '头像颜色', avatarIcon: '头像图标',
    changePassword: '更改密码', newPassword: '新密码...',
    confirmPassword: '确认密码...', aiPreferences: 'AI偏好',
    appearance: '外观', darkMode: '深色模式', darkEnabled: '深色主题已启用',
    lightEnabled: '浅色主题已启用', sidebarOrder: '侧边栏顺序',
    sidebarDrag: '拖放以重新排列导航按钮。',
    saveSidebarOrder: '保存侧边栏顺序', account: '账户',
    signOutDesc: '退出您的账户。', signOut: '退出登录',
    language: '语言', languageDesc: '选择您的首选语言',
    addWord: '添加单词', practice: '练习', difficult: '困难',
    search: '搜索...', masteryProgress: '掌握进度',
    words: '个单词', mastered: '已掌握', noDifficultWords: '没有困难单词',
    noWordsFound: '未找到单词', noWordsYet: '还没有单词',
    greatNoDifficult: '太棒了！没有标记为困难的单词',
    tryDifferentSearch: '尝试不同的搜索词', addFirstWord: '添加您的第一个单词',
    showingDifficult: '显示需要复习的困难单词',
    askAnything: '问任何关于学习的问题...', howCanIHelp: '我能帮你什么？',
    aiDesc: '问我任何关于学习的问题。',
    signInToUse: '登录使用', analyzing: '分析中...', thinking: '思考中...',
    generating: '生成中...', processing: '处理中...',
    uploadImage: '上传图片', takePhoto: '拍照',
    signIn: '登录/创建账户', myProfile: '我的资料',
    signInBtn: '登录', createAccountBtn: '创建账户',
    welcomeBack: '欢迎回来', createYourAccount: '创建您的账户',
    continueYourJourney: '继续您的学习之旅',
    startYourJourney: '今天开始您的学习之旅',
    email: '邮箱', password: '密码', confirmPasswordLabel: '确认密码',
    howShouldWeCallYou: '我们怎么称呼您？',
    dontHaveAccount: '没有账户？', signUpLink: '注册',
    alreadyHaveAccount: '已有账户？', signInLink: '登录',
    backToHome: '返回首页', loading: '加载中...',
    learnSmarter: '更聪明地学习',
    authFeatureDesc: 'AI工具、智能组织和专注学习——您需要的一切。',
    emailNotAvailable: '此邮箱不可用',
    displayNameRequired: '请输入显示名称',
    signupFailed: '创建账户失败', signinFailed: '登录失败',
    accountCreated: '账户创建成功！', signedIn: '登录成功！',
    youAreOffline: '离线 — 数据已本地保存', hide: '隐藏',
    customizeAi: '自定义AI的回复方式。', aiPlaceholder: '例如：简单解释，使用示例...',
    saveAiPrefs: '保存AI偏好', changingPassword: '更改中...',
    passwordChanged: '密码已更改', passwordsDontMatch: '密码不匹配',
    passwordTooShort: '至少6个字符', displayNameUpdated: '名称已更新',
    aiPrefsUpdated: 'AI偏好已更新', sidebarOrderSaved: '顺序已保存',
    testComplete: '测试完成！', wordsReviewed: '个单词已复习',
    easy: '简单', hard: '困难', failed: '失败', wordsToReview: '需要复习的单词',
    testAgain: '再次测试', backToVocabulary: '返回词汇',
    numberOfWords: '单词数量', testType: '测试类型', testFormat: '测试格式',
    flashcards: '闪卡', multipleChoice: '选择题',
    flipToReveal: '翻转查看含义', pickCorrect: '选择正确答案',
    random: '随机', focus: '重点', smartReview: '智能复习',
    randomDesc: '随机选择', focusDesc: '仅困难单词',
    smartDesc: '需要复习的单词', startTest: '开始测试',
    whatDoesWordMean: '这个词是什么意思？', needsMorePractice: '需要更多练习',
    back: '返回',
    yourUltimate: '您的终极', studyCompanion: '学习伙伴',
    homeDesc: 'AI工具、智能组织和专注学习——一站式学习平台。',
    getStartedFree: '免费开始', features: '功能',
    everythingYouNeed: '您需要的一切',
    readyToTransform: '准备好改变学习习惯了吗？',
    joinStudents: '加入使用StudyHub的学生行列。',
    createFreeAccount: '创建免费账户',
    welcomeBackUser: '欢迎回来，',
    homeWelcomeDesc: 'StudyHub是您的一站式学术工具包。',
    goToMaterials: '我的资料',
    installApp: '📱 安装此应用以供离线使用',
    aiStudyAssistant: 'AI学习助手', aiStudyAssistantDesc: '与智能AI导师交流。',
    organizeMaterials: '整理资料', organizeMaterialsDesc: '将一切整理有序。',
    pomodoroTimerTitle: '番茄钟', pomodoroTimerDesc: '保持专注。',
    vocabFlashcards: '词汇和闪卡', vocabFlashcardsDesc: '建立您的词汇量。',
    signInToViewMaterials: '登录查看资料', createAccountToSave: '创建账户以保存',
    addMaterial: '添加资料', noMaterialsYet: '还没有资料', addFirstMaterial: '添加第一个资料！',
    addTask: '添加任务', total: '总计', completed: '已完成', urgent: '紧急', overdue: '逾期',
    taskTitle: '任务标题...', taskDescription: '描述（可选）',
    deadline: '截止日期', importance: '重要性',
    urgentLabel: '紧急', mediumLabel: '中等', lowLabel: '低',
    noTasks: '暂无任务', addFirstTask: '添加第一个任务',
    signInForTodos: '登录使用待办事项',
    messagesTitle: '消息和投票', noMessages: '暂无消息', markAllRead: '全部标为已读',
    suggestionsTitle: '建议', addSuggestion: '添加建议',
    suggestionTitle: '标题', suggestionDesc: '描述',
    noSuggestions: '暂无建议', submitSuggestion: '提交',
    tableCreatorTitle: '创建表格', tableCreatorDesc: '设计漂亮的表格。',
    study: '学习', shortBreak: '短休息', longBreak: '长休息',
  },
  ja: {
    home: 'ホーム', studyMaterials: '学習資料', vocabulary: '語彙',
    aiStudyChat: 'AIチャット', createTable: 'テーブル作成', pomodoroTimer: 'ポモドーロ',
    suggestions: '提案', messages: 'メッセージ', todoList: 'やることリスト', technicalSupport: 'テクニカルサポート',
    settings: '設定', profile: 'プロフィール', displayName: '表示名',
    save: '保存', avatarColor: 'アバターの色', avatarIcon: 'アバターアイコン',
    changePassword: 'パスワード変更', newPassword: '新しいパスワード...',
    confirmPassword: 'パスワード確認...', aiPreferences: 'AI設定',
    appearance: '外観', darkMode: 'ダークモード', darkEnabled: 'ダークテーマ有効',
    lightEnabled: 'ライトテーマ有効', sidebarOrder: 'サイドバー順序',
    sidebarDrag: 'ドラッグ＆ドロップで並べ替え。',
    saveSidebarOrder: '順序を保存', account: 'アカウント',
    signOutDesc: 'このデバイスからサインアウト。', signOut: 'サインアウト',
    language: '言語', languageDesc: 'お好みの言語を選択',
    addWord: '単語追加', practice: '練習', difficult: '難しい',
    search: '検索...', masteryProgress: '習得進捗',
    words: '語', mastered: '習得済み', noDifficultWords: '難しい単語なし',
    noWordsFound: '単語が見つかりません', noWordsYet: 'まだ単語がありません',
    greatNoDifficult: '素晴らしい！難しい単語はありません',
    tryDifferentSearch: '別の検索語を試してください', addFirstWord: '最初の単語を追加',
    showingDifficult: '復習が必要な難しい単語を表示',
    askAnything: '何でも聞いてください...', howCanIHelp: '何かお手伝いできますか？',
    aiDesc: '学習に関する質問をどうぞ。',
    signInToUse: 'ログインして使用', analyzing: '分析中...', thinking: '思考中...',
    generating: '生成中...', processing: '処理中...',
    uploadImage: '画像アップロード', takePhoto: '写真撮影',
    signIn: 'ログイン/アカウント作成', myProfile: 'マイプロフィール',
    signInBtn: 'ログイン', createAccountBtn: 'アカウント作成',
    welcomeBack: 'おかえりなさい', createYourAccount: 'アカウント作成',
    continueYourJourney: '学習を続けましょう',
    startYourJourney: '今日から学習を始めましょう',
    email: 'メール', password: 'パスワード', confirmPasswordLabel: 'パスワード確認',
    howShouldWeCallYou: 'お名前は？',
    dontHaveAccount: 'アカウントがない？', signUpLink: '登録',
    alreadyHaveAccount: 'アカウントがある？', signInLink: 'ログイン',
    backToHome: 'ホームに戻る', loading: '読み込み中...',
    learnSmarter: 'もっと賢く学ぼう',
    authFeatureDesc: 'AIツール、スマートな整理、集中学習セッション。',
    emailNotAvailable: 'このメールアドレスは使用できません',
    displayNameRequired: '表示名を入力してください',
    signupFailed: 'アカウント作成に失敗', signinFailed: 'ログインに失敗',
    accountCreated: 'アカウント作成成功！', signedIn: 'ログイン成功！',
    youAreOffline: 'オフライン — データはローカルに保存', hide: '非表示',
    customizeAi: 'AIの応答をカスタマイズ。', aiPlaceholder: '例：簡単に説明、例を使用...',
    saveAiPrefs: 'AI設定を保存', changingPassword: '変更中...',
    passwordChanged: 'パスワード変更済み', passwordsDontMatch: 'パスワードが一致しません',
    passwordTooShort: '6文字以上必要', displayNameUpdated: '名前更新済み',
    aiPrefsUpdated: 'AI設定更新済み', sidebarOrderSaved: '順序保存済み',
    testComplete: 'テスト完了！', wordsReviewed: '語復習済み',
    easy: '簡単', hard: '難しい', failed: '不合格', wordsToReview: '復習する単語',
    testAgain: '再テスト', backToVocabulary: '語彙に戻る',
    numberOfWords: '単語数', testType: 'テストタイプ', testFormat: 'テスト形式',
    flashcards: 'フラッシュカード', multipleChoice: '選択問題',
    flipToReveal: 'めくって確認', pickCorrect: '正解を選択',
    random: 'ランダム', focus: '集中', smartReview: 'スマート復習',
    randomDesc: 'ランダム選択', focusDesc: '難しい単語のみ',
    smartDesc: '復習が必要な単語', startTest: 'テスト開始',
    whatDoesWordMean: 'この単語の意味は？', needsMorePractice: 'もっと練習が必要',
    back: '戻る',
    yourUltimate: '究極の', studyCompanion: '学習パートナー',
    homeDesc: 'AIツール、スマートな整理、集中学習セッション。',
    getStartedFree: '無料で始める', features: '機能',
    everythingYouNeed: '成功に必要なすべて',
    readyToTransform: '学習習慣を変える準備はできましたか？',
    joinStudents: 'StudyHubを使う学生に参加しましょう。',
    createFreeAccount: '無料アカウントを作成',
    welcomeBackUser: 'おかえりなさい、',
    homeWelcomeDesc: 'StudyHubはあなたの学術ツールキットです。',
    goToMaterials: '資料へ',
    installApp: '📱 オフラインアクセスのためにアプリをインストール',
    aiStudyAssistant: 'AI学習アシスタント', aiStudyAssistantDesc: 'AIチューターと会話。',
    organizeMaterials: '資料整理', organizeMaterialsDesc: 'すべてを整理整頓。',
    pomodoroTimerTitle: 'ポモドーロ', pomodoroTimerDesc: '集中力を維持。',
    vocabFlashcards: '語彙とフラッシュカード', vocabFlashcardsDesc: '語彙力を強化。',
    signInToViewMaterials: 'ログインして資料を表示', createAccountToSave: 'アカウントを作成して保存',
    addMaterial: '資料追加', noMaterialsYet: 'まだ資料がありません', addFirstMaterial: '最初の資料を追加！',
    addTask: 'タスク追加', total: '合計', completed: '完了', urgent: '緊急', overdue: '期限切れ',
    taskTitle: 'タスク名...', taskDescription: '説明（任意）',
    deadline: '期限', importance: '重要度',
    urgentLabel: '緊急', mediumLabel: '中', lowLabel: '低',
    noTasks: 'タスクなし', addFirstTask: '最初のタスクを追加',
    signInForTodos: 'ログインしてタスク管理',
    messagesTitle: 'メッセージと投票', noMessages: 'メッセージなし', markAllRead: 'すべて既読',
    suggestionsTitle: '提案', addSuggestion: '提案を追加',
    suggestionTitle: 'タイトル', suggestionDesc: '説明',
    noSuggestions: '提案なし', submitSuggestion: '送信',
    tableCreatorTitle: 'テーブル作成', tableCreatorDesc: '美しいテーブルを作成。',
    study: '学習', shortBreak: '短い休憩', longBreak: '長い休憩',
  },
  hi: {
    home: 'होम', studyMaterials: 'अध्ययन सामग्री', vocabulary: 'शब्दावली',
    aiStudyChat: 'AI चैट', createTable: 'तालिका बनाएं', pomodoroTimer: 'पोमोडोरो टाइमर',
    suggestions: 'सुझाव', messages: 'संदेश', todoList: 'कार्य सूची',
    settings: 'सेटिंग्स', profile: 'प्रोफ़ाइल', displayName: 'प्रदर्शन नाम',
    save: 'सहेजें', avatarColor: 'अवतार रंग', avatarIcon: 'अवतार आइकन',
    changePassword: 'पासवर्ड बदलें', newPassword: 'नया पासवर्ड...',
    confirmPassword: 'पासवर्ड की पुष्टि...', aiPreferences: 'AI प्राथमिकताएं',
    appearance: 'दिखावट', darkMode: 'डार्क मोड', darkEnabled: 'डार्क थीम सक्रिय',
    lightEnabled: 'लाइट थीम सक्रिय', sidebarOrder: 'साइडबार क्रम',
    sidebarDrag: 'नेविगेशन बटन पुनर्व्यवस्थित करने के लिए ड्रैग और ड्रॉप करें।',
    saveSidebarOrder: 'साइडबार क्रम सहेजें', account: 'खाता',
    signOutDesc: 'इस डिवाइस से साइन आउट करें।', signOut: 'साइन आउट',
    language: 'भाषा', languageDesc: 'अपनी पसंदीदा भाषा चुनें',
    addWord: 'शब्द जोड़ें', practice: 'अभ्यास', difficult: 'कठिन',
    search: 'खोजें...', masteryProgress: 'महारत प्रगति',
    words: 'शब्द', mastered: 'महारत हासिल', noDifficultWords: 'कोई कठिन शब्द नहीं',
    noWordsFound: 'कोई शब्द नहीं मिला', noWordsYet: 'अभी तक कोई शब्द नहीं',
    greatNoDifficult: 'बढ़िया! कोई कठिन शब्द नहीं',
    tryDifferentSearch: 'कोई और खोज शब्द आज़माएं', addFirstWord: 'अपना पहला शब्द जोड़ें',
    showingDifficult: 'कठिन शब्द दिखा रहे हैं',
    askAnything: 'कुछ भी पूछें...', howCanIHelp: 'मैं कैसे मदद कर सकता हूं?',
    aiDesc: 'अपनी पढ़ाई के बारे में कुछ भी पूछें।',
    signInToUse: 'उपयोग करने के लिए साइन इन करें', analyzing: 'विश्लेषण...', thinking: 'सोच रहा...',
    generating: 'प्रतिक्रिया बना रहा...', processing: 'प्रसंस्करण...',
    uploadImage: 'छवि अपलोड', takePhoto: 'फ़ोटो लें',
    signIn: 'साइन इन / खाता बनाएं', myProfile: 'मेरा प्रोफ़ाइल',
    signInBtn: 'साइन इन', createAccountBtn: 'खाता बनाएं',
    welcomeBack: 'वापसी पर स्वागत', createYourAccount: 'अपना खाता बनाएं',
    continueYourJourney: 'अपनी सीखने की यात्रा जारी रखें',
    startYourJourney: 'आज अपनी सीखने की यात्रा शुरू करें',
    email: 'ईमेल', password: 'पासवर्ड', confirmPasswordLabel: 'पासवर्ड की पुष्टि',
    howShouldWeCallYou: 'हम आपको क्या बुलाएं?',
    dontHaveAccount: 'खाता नहीं है?', signUpLink: 'साइन अप',
    alreadyHaveAccount: 'पहले से खाता है?', signInLink: 'साइन इन',
    backToHome: 'होम पर वापस', loading: 'लोड हो रहा...',
    learnSmarter: 'चतुराई से सीखें',
    authFeatureDesc: 'AI उपकरण, स्मार्ट संगठन और केंद्रित अध्ययन सत्र।',
    emailNotAvailable: 'यह ईमेल उपलब्ध नहीं है',
    displayNameRequired: 'कृपया प्रदर्शन नाम दर्ज करें',
    signupFailed: 'खाता बनाने में विफल', signinFailed: 'साइन इन विफल',
    accountCreated: 'खाता सफलतापूर्वक बनाया गया!', signedIn: 'सफलतापूर्वक साइन इन!',
    youAreOffline: 'ऑफ़लाइन — डेटा स्थानीय रूप से सहेजा गया', hide: 'छिपाएं',
    customizeAi: 'AI की प्रतिक्रिया अनुकूलित करें।', aiPlaceholder: 'उदा: सरल शब्दों में समझाएं...',
    saveAiPrefs: 'AI प्राथमिकताएं सहेजें', changingPassword: 'बदल रहा...',
    passwordChanged: 'पासवर्ड बदला गया', passwordsDontMatch: 'पासवर्ड मेल नहीं खाते',
    passwordTooShort: 'कम से कम 6 अक्षर', displayNameUpdated: 'नाम अपडेट किया गया',
    aiPrefsUpdated: 'AI प्राथमिकताएं अपडेट', sidebarOrderSaved: 'क्रम सहेजा गया',
    testComplete: 'परीक्षा पूर्ण!', wordsReviewed: 'शब्दों की समीक्षा',
    easy: 'आसान', hard: 'कठिन', failed: 'असफल', wordsToReview: 'समीक्षा के लिए शब्द',
    testAgain: 'फिर से परीक्षा', backToVocabulary: 'शब्दावली पर वापस',
    numberOfWords: 'शब्दों की संख्या', testType: 'परीक्षा प्रकार', testFormat: 'परीक्षा प्रारूप',
    flashcards: 'फ्लैशकार्ड', multipleChoice: 'बहुविकल्पी',
    flipToReveal: 'अर्थ देखने के लिए पलटें', pickCorrect: 'सही उत्तर चुनें',
    random: 'यादृच्छिक', focus: 'केंद्रित', smartReview: 'स्मार्ट समीक्षा',
    randomDesc: 'यादृच्छिक चयन', focusDesc: 'केवल कठिन शब्द',
    smartDesc: 'समीक्षा की आवश्यकता वाले शब्द', startTest: 'परीक्षा शुरू',
    whatDoesWordMean: 'इस शब्द का अर्थ?', needsMorePractice: 'और अभ्यास चाहिए',
    back: 'वापस',
    yourUltimate: 'आपका सर्वोत्तम', studyCompanion: 'अध्ययन साथी',
    homeDesc: 'AI उपकरण, स्मार्ट संगठन और अध्ययन सत्र — सब कुछ एक जगह।',
    getStartedFree: 'मुफ्त में शुरू करें', features: 'सुविधाएं',
    everythingYouNeed: 'सफलता के लिए सब कुछ',
    readyToTransform: 'अपनी अध्ययन आदतें बदलने के लिए तैयार?',
    joinStudents: 'StudyHub का उपयोग करने वाले छात्रों से जुड़ें।',
    createFreeAccount: 'मुफ्त खाता बनाएं',
    welcomeBackUser: 'वापसी पर स्वागत,',
    homeWelcomeDesc: 'StudyHub आपका ऑल-इन-वन अकादमिक टूलकिट है।',
    goToMaterials: 'मेरी सामग्री',
    installApp: '📱 ऑफ़लाइन एक्सेस के लिए ऐप इंस्टॉल करें',
    aiStudyAssistant: 'AI अध्ययन सहायक', aiStudyAssistantDesc: 'AI ट्यूटर से बात करें।',
    organizeMaterials: 'सामग्री व्यवस्थित करें', organizeMaterialsDesc: 'सब कुछ व्यवस्थित रखें।',
    pomodoroTimerTitle: 'पोमोडोरो टाइमर', pomodoroTimerDesc: 'ध्यान केंद्रित रखें।',
    vocabFlashcards: 'शब्दावली और कार्ड', vocabFlashcardsDesc: 'शब्दावली बनाएं।',
    signInToViewMaterials: 'सामग्री देखने के लिए साइन इन', createAccountToSave: 'सहेजने के लिए खाता बनाएं',
    addMaterial: 'सामग्री जोड़ें', noMaterialsYet: 'अभी कोई सामग्री नहीं', addFirstMaterial: 'पहली सामग्री जोड़ें!',
    addTask: 'कार्य जोड़ें', total: 'कुल', completed: 'पूर्ण', urgent: 'जरूरी', overdue: 'विलंबित',
    taskTitle: 'कार्य शीर्षक...', taskDescription: 'विवरण (वैकल्पिक)',
    deadline: 'समय सीमा', importance: 'महत्व',
    urgentLabel: 'जरूरी', mediumLabel: 'मध्यम', lowLabel: 'कम',
    noTasks: 'कोई कार्य नहीं', addFirstTask: 'पहला कार्य जोड़ें',
    signInForTodos: 'कार्य सूची के लिए साइन इन',
    messagesTitle: 'संदेश और मतदान', noMessages: 'कोई संदेश नहीं', markAllRead: 'सब पढ़ा हुआ',
    suggestionsTitle: 'सुझाव', addSuggestion: 'सुझाव जोड़ें',
    suggestionTitle: 'शीर्षक', suggestionDesc: 'विवरण',
    noSuggestions: 'कोई सुझाव नहीं', submitSuggestion: 'भेजें',
    tableCreatorTitle: 'तालिका बनाएं', tableCreatorDesc: 'सुंदर तालिकाएं बनाएं।',
    study: 'अध्ययन', shortBreak: 'छोटा ब्रेक', longBreak: 'लंबा ब्रेक',
  },
  es: {
    home: 'Inicio', studyMaterials: 'Material de estudio', vocabulary: 'Vocabulario',
    aiStudyChat: 'Chat IA', createTable: 'Crear tabla', pomodoroTimer: 'Temporizador Pomodoro',
    suggestions: 'Sugerencias', messages: 'Mensajes', todoList: 'Lista de tareas',
    settings: 'Configuración', profile: 'Perfil', displayName: 'Nombre visible',
    save: 'Guardar', avatarColor: 'Color de avatar', avatarIcon: 'Ícono de avatar',
    changePassword: 'Cambiar contraseña', newPassword: 'Nueva contraseña...',
    confirmPassword: 'Confirmar contraseña...', aiPreferences: 'Preferencias IA',
    appearance: 'Apariencia', darkMode: 'Modo oscuro', darkEnabled: 'Tema oscuro activado',
    lightEnabled: 'Tema claro activado', sidebarOrder: 'Orden de la barra lateral',
    sidebarDrag: 'Arrastra para reordenar los botones de navegación.',
    saveSidebarOrder: 'Guardar orden', account: 'Cuenta',
    signOutDesc: 'Cerrar sesión en este dispositivo.', signOut: 'Cerrar sesión',
    language: 'Idioma', languageDesc: 'Elige tu idioma preferido',
    addWord: 'Agregar palabra', practice: 'Practicar', difficult: 'Difícil',
    search: 'Buscar...', masteryProgress: 'Progreso de dominio',
    words: 'palabras', mastered: 'dominadas', noDifficultWords: 'Sin palabras difíciles',
    noWordsFound: 'No se encontraron palabras', noWordsYet: 'Aún no hay palabras',
    greatNoDifficult: '¡Genial! No hay palabras difíciles',
    tryDifferentSearch: 'Intenta otro término', addFirstWord: 'Agrega tu primera palabra',
    showingDifficult: 'Mostrando palabras difíciles',
    askAnything: 'Pregunta lo que quieras...', howCanIHelp: '¿Cómo puedo ayudarte?',
    aiDesc: 'Pregúntame cualquier cosa sobre tus estudios.',
    signInToUse: 'Inicia sesión', analyzing: 'Analizando...', thinking: 'Pensando...',
    generating: 'Generando...', processing: 'Procesando...',
    uploadImage: 'Subir imagen', takePhoto: 'Tomar foto',
    signIn: 'Iniciar sesión / Crear cuenta', myProfile: 'Mi perfil',
    signInBtn: 'Iniciar sesión', createAccountBtn: 'Crear cuenta',
    welcomeBack: 'Bienvenido de vuelta', createYourAccount: 'Crea tu cuenta',
    continueYourJourney: 'Continúa tu camino de aprendizaje',
    startYourJourney: 'Comienza tu camino de aprendizaje hoy',
    email: 'Email', password: 'Contraseña', confirmPasswordLabel: 'Confirmar contraseña',
    howShouldWeCallYou: '¿Cómo debemos llamarte?',
    dontHaveAccount: '¿No tienes cuenta?', signUpLink: 'Regístrate',
    alreadyHaveAccount: '¿Ya tienes cuenta?', signInLink: 'Inicia sesión',
    backToHome: 'Volver al inicio', loading: 'Cargando...',
    learnSmarter: 'Aprende más inteligentemente',
    authFeatureDesc: 'Herramientas IA, organización inteligente y sesiones de estudio enfocadas.',
    emailNotAvailable: 'Este correo no está disponible',
    displayNameRequired: 'Por favor ingresa un nombre',
    signupFailed: 'Error al crear la cuenta', signinFailed: 'Error al iniciar sesión',
    accountCreated: '¡Cuenta creada exitosamente!', signedIn: '¡Sesión iniciada!',
    youAreOffline: 'Sin conexión — datos guardados localmente', hide: 'Ocultar',
    customizeAi: 'Personaliza las respuestas de la IA.',
    aiPlaceholder: 'Ej: Explica de forma sencilla...',
    saveAiPrefs: 'Guardar preferencias IA', changingPassword: 'Cambiando...',
    passwordChanged: 'Contraseña cambiada', passwordsDontMatch: 'Las contraseñas no coinciden',
    passwordTooShort: 'Mínimo 6 caracteres', displayNameUpdated: 'Nombre actualizado',
    aiPrefsUpdated: 'Preferencias IA actualizadas', sidebarOrderSaved: 'Orden guardado',
    testComplete: '¡Prueba completa!', wordsReviewed: 'palabras revisadas',
    easy: 'Fácil', hard: 'Difícil', failed: 'Fallido', wordsToReview: 'Palabras a repasar',
    testAgain: 'Repetir prueba', backToVocabulary: 'Volver al vocabulario',
    numberOfWords: 'Número de palabras', testType: 'Tipo de prueba', testFormat: 'Formato de prueba',
    flashcards: 'Tarjetas', multipleChoice: 'Opción múltiple',
    flipToReveal: 'Voltea para revelar', pickCorrect: 'Elige la respuesta correcta',
    random: 'Aleatorio', focus: 'Enfocado', smartReview: 'Repaso inteligente',
    randomDesc: 'Selección aleatoria', focusDesc: 'Solo palabras difíciles',
    smartDesc: 'Palabras que necesitan repaso', startTest: 'Iniciar prueba',
    whatDoesWordMean: '¿Qué significa esta palabra?', needsMorePractice: 'Necesita más práctica',
    back: 'Volver',
    yourUltimate: 'Tu compañero', studyCompanion: 'de estudio definitivo',
    homeDesc: 'Herramientas IA, organización inteligente y sesiones de estudio — todo en un solo lugar.',
    getStartedFree: 'Empezar gratis', features: 'Características',
    everythingYouNeed: 'Todo lo que necesitas para triunfar',
    readyToTransform: '¿Listo para transformar tus hábitos de estudio?',
    joinStudents: 'Únete a los estudiantes que usan StudyHub.',
    createFreeAccount: 'Crea tu cuenta gratis',
    welcomeBackUser: 'Bienvenido de vuelta,',
    homeWelcomeDesc: 'StudyHub es tu kit de herramientas académicas todo en uno.',
    goToMaterials: 'Mis materiales',
    installApp: '📱 Instala esta app para acceso sin conexión',
    aiStudyAssistant: 'Asistente IA', aiStudyAssistantDesc: 'Chatea con un tutor IA.',
    organizeMaterials: 'Organizar materiales', organizeMaterialsDesc: 'Mantén todo organizado.',
    pomodoroTimerTitle: 'Temporizador Pomodoro', pomodoroTimerDesc: 'Mantén el enfoque.',
    vocabFlashcards: 'Vocabulario y tarjetas', vocabFlashcardsDesc: 'Construye tu vocabulario.',
    signInToViewMaterials: 'Inicia sesión para ver materiales', createAccountToSave: 'Crea una cuenta para guardar',
    addMaterial: 'Agregar material', noMaterialsYet: 'Sin materiales aún', addFirstMaterial: '¡Agrega tu primer material!',
    addTask: 'Agregar tarea', total: 'Total', completed: 'Completado', urgent: 'Urgente', overdue: 'Atrasado',
    taskTitle: 'Título de la tarea...', taskDescription: 'Descripción (opcional)',
    deadline: 'Fecha límite', importance: 'Importancia',
    urgentLabel: 'Urgente', mediumLabel: 'Medio', lowLabel: 'Bajo',
    noTasks: 'Sin tareas', addFirstTask: 'Agrega tu primera tarea',
    signInForTodos: 'Inicia sesión para tareas',
    messagesTitle: 'Mensajes y encuestas', noMessages: 'Sin mensajes', markAllRead: 'Marcar todo leído',
    suggestionsTitle: 'Sugerencias', addSuggestion: 'Agregar sugerencia',
    suggestionTitle: 'Título', suggestionDesc: 'Descripción',
    noSuggestions: 'Sin sugerencias', submitSuggestion: 'Enviar',
    tableCreatorTitle: 'Crear tabla', tableCreatorDesc: 'Diseña tablas hermosas.',
    study: 'Estudio', shortBreak: 'Descanso corto', longBreak: 'Descanso largo',
  },
  pt: {
    home: 'Início', studyMaterials: 'Material de estudo', vocabulary: 'Vocabulário',
    aiStudyChat: 'Chat IA', createTable: 'Criar tabela', pomodoroTimer: 'Temporizador Pomodoro',
    suggestions: 'Sugestões', messages: 'Mensagens', todoList: 'Lista de tarefas',
    settings: 'Configurações', profile: 'Perfil', displayName: 'Nome de exibição',
    save: 'Salvar', avatarColor: 'Cor do avatar', avatarIcon: 'Ícone do avatar',
    changePassword: 'Alterar senha', newPassword: 'Nova senha...',
    confirmPassword: 'Confirmar senha...', aiPreferences: 'Preferências IA',
    appearance: 'Aparência', darkMode: 'Modo escuro', darkEnabled: 'Tema escuro ativado',
    lightEnabled: 'Tema claro ativado', sidebarOrder: 'Ordem da barra lateral',
    sidebarDrag: 'Arraste para reordenar os botões de navegação.',
    saveSidebarOrder: 'Salvar ordem', account: 'Conta',
    signOutDesc: 'Sair da sua conta neste dispositivo.', signOut: 'Sair',
    language: 'Idioma', languageDesc: 'Escolha seu idioma preferido',
    addWord: 'Adicionar palavra', practice: 'Praticar', difficult: 'Difícil',
    search: 'Pesquisar...', masteryProgress: 'Progresso de domínio',
    words: 'palavras', mastered: 'dominadas', noDifficultWords: 'Sem palavras difíceis',
    noWordsFound: 'Nenhuma palavra encontrada', noWordsYet: 'Nenhuma palavra ainda',
    greatNoDifficult: 'Ótimo! Nenhuma palavra difícil',
    tryDifferentSearch: 'Tente outro termo', addFirstWord: 'Adicione sua primeira palavra',
    showingDifficult: 'Mostrando palavras difíceis',
    askAnything: 'Pergunte qualquer coisa...', howCanIHelp: 'Como posso ajudar?',
    aiDesc: 'Pergunte-me qualquer coisa sobre seus estudos.',
    signInToUse: 'Faça login para usar', analyzing: 'Analisando...', thinking: 'Pensando...',
    generating: 'Gerando...', processing: 'Processando...',
    uploadImage: 'Enviar imagem', takePhoto: 'Tirar foto',
    signIn: 'Entrar / Criar conta', myProfile: 'Meu perfil',
    signInBtn: 'Entrar', createAccountBtn: 'Criar conta',
    welcomeBack: 'Bem-vindo de volta', createYourAccount: 'Crie sua conta',
    continueYourJourney: 'Continue sua jornada de aprendizado',
    startYourJourney: 'Comece sua jornada de aprendizado hoje',
    email: 'Email', password: 'Senha', confirmPasswordLabel: 'Confirmar senha',
    howShouldWeCallYou: 'Como devemos chamá-lo?',
    dontHaveAccount: 'Não tem conta?', signUpLink: 'Cadastre-se',
    alreadyHaveAccount: 'Já tem conta?', signInLink: 'Entrar',
    backToHome: 'Voltar ao início', loading: 'Carregando...',
    learnSmarter: 'Aprenda de forma mais inteligente',
    authFeatureDesc: 'Ferramentas IA, organização inteligente e sessões de estudo focadas.',
    emailNotAvailable: 'Este email não está disponível',
    displayNameRequired: 'Por favor insira um nome de exibição',
    signupFailed: 'Falha ao criar conta', signinFailed: 'Falha ao entrar',
    accountCreated: 'Conta criada com sucesso!', signedIn: 'Login realizado com sucesso!',
    youAreOffline: 'Offline — dados salvos localmente', hide: 'Ocultar',
    customizeAi: 'Personalize as respostas da IA.',
    aiPlaceholder: 'Ex: Explique de forma simples...',
    saveAiPrefs: 'Salvar preferências IA', changingPassword: 'Alterando...',
    passwordChanged: 'Senha alterada', passwordsDontMatch: 'As senhas não coincidem',
    passwordTooShort: 'Mínimo 6 caracteres', displayNameUpdated: 'Nome atualizado',
    aiPrefsUpdated: 'Preferências IA atualizadas', sidebarOrderSaved: 'Ordem salva',
    testComplete: 'Teste completo!', wordsReviewed: 'palavras revisadas',
    easy: 'Fácil', hard: 'Difícil', failed: 'Reprovado', wordsToReview: 'Palavras para revisar',
    testAgain: 'Testar novamente', backToVocabulary: 'Voltar ao vocabulário',
    numberOfWords: 'Número de palavras', testType: 'Tipo de teste', testFormat: 'Formato de teste',
    flashcards: 'Cartões', multipleChoice: 'Múltipla escolha',
    flipToReveal: 'Vire para revelar', pickCorrect: 'Escolha a resposta correta',
    random: 'Aleatório', focus: 'Focado', smartReview: 'Revisão inteligente',
    randomDesc: 'Seleção aleatória', focusDesc: 'Apenas palavras difíceis',
    smartDesc: 'Palavras que precisam de revisão', startTest: 'Iniciar teste',
    whatDoesWordMean: 'O que esta palavra significa?', needsMorePractice: 'Precisa de mais prática',
    back: 'Voltar',
    yourUltimate: 'Seu companheiro', studyCompanion: 'de estudo definitivo',
    homeDesc: 'Ferramentas IA, organização inteligente e sessões de estudo — tudo em um só lugar.',
    getStartedFree: 'Comece grátis', features: 'Recursos',
    everythingYouNeed: 'Tudo que você precisa para ter sucesso',
    readyToTransform: 'Pronto para transformar seus hábitos de estudo?',
    joinStudents: 'Junte-se aos alunos que usam o StudyHub.',
    createFreeAccount: 'Crie sua conta grátis',
    welcomeBackUser: 'Bem-vindo de volta,',
    homeWelcomeDesc: 'StudyHub é seu kit de ferramentas acadêmico completo.',
    goToMaterials: 'Meus materiais',
    installApp: '📱 Instale este app para acesso offline',
    aiStudyAssistant: 'Assistente IA', aiStudyAssistantDesc: 'Converse com um tutor IA.',
    organizeMaterials: 'Organizar materiais', organizeMaterialsDesc: 'Mantenha tudo organizado.',
    pomodoroTimerTitle: 'Temporizador Pomodoro', pomodoroTimerDesc: 'Mantenha o foco.',
    vocabFlashcards: 'Vocabulário e cartões', vocabFlashcardsDesc: 'Construa seu vocabulário.',
    signInToViewMaterials: 'Faça login para ver materiais', createAccountToSave: 'Crie uma conta para salvar',
    addMaterial: 'Adicionar material', noMaterialsYet: 'Nenhum material ainda', addFirstMaterial: 'Adicione seu primeiro material!',
    addTask: 'Adicionar tarefa', total: 'Total', completed: 'Concluído', urgent: 'Urgente', overdue: 'Atrasado',
    taskTitle: 'Título da tarefa...', taskDescription: 'Descrição (opcional)',
    deadline: 'Prazo', importance: 'Importância',
    urgentLabel: 'Urgente', mediumLabel: 'Médio', lowLabel: 'Baixo',
    noTasks: 'Nenhuma tarefa', addFirstTask: 'Adicione sua primeira tarefa',
    signInForTodos: 'Faça login para tarefas',
    messagesTitle: 'Mensagens e enquetes', noMessages: 'Nenhuma mensagem', markAllRead: 'Marcar tudo lido',
    suggestionsTitle: 'Sugestões', addSuggestion: 'Adicionar sugestão',
    suggestionTitle: 'Título', suggestionDesc: 'Descrição',
    noSuggestions: 'Nenhuma sugestão', submitSuggestion: 'Enviar',
    tableCreatorTitle: 'Criar tabela', tableCreatorDesc: 'Crie tabelas bonitas.',
    study: 'Estudo', shortBreak: 'Pausa curta', longBreak: 'Pausa longa',
  },
};

const RTL_LANGUAGES: Language[] = ['ar'];

const LANGUAGE_INFO: { code: Language; name: string; nativeName: string; flag: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
  dir: 'ltr' | 'rtl';
  LANGUAGE_INFO: typeof LANGUAGE_INFO;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
  isRTL: false,
  dir: 'ltr',
  LANGUAGE_INFO,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { settings, updateSettings } = useUserSettings();
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    if (settings?.language) {
      setLanguageState(settings.language as Language);
    }
  }, [settings?.language]);

  // Apply dir and lang to document
  useEffect(() => {
    const isRTL = RTL_LANGUAGES.includes(language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    updateSettings({ language: lang } as any);
  }, [updateSettings]);

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  }, [language]);

  const isRTL = RTL_LANGUAGES.includes(language);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL, dir: isRTL ? 'rtl' : 'ltr', LANGUAGE_INFO }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
